-- LLM Bible Community schema
-- Run once in Supabase SQL Editor. Safe to re-run for upgrades.
-- Auth passwords are managed by Supabase Auth (auth.users). Never store plaintext passwords here.

create extension if not exists pgcrypto with schema extensions;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null check (char_length(display_name) between 2 and 40),
  role text not null default 'user' check (role in ('user','admin')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.submissions (
  id uuid primary key default gen_random_uuid(),
  author_id uuid not null references public.profiles(id) on delete cascade,
  author_display_name text not null default '회원' check (char_length(author_display_name) between 1 and 40),
  slug text not null unique,
  title text not null check (char_length(title) between 5 and 100),
  category text not null check (char_length(category) between 1 and 40),
  summary text not null check (char_length(summary) between 20 and 500),
  prompt_text text not null check (char_length(prompt_text) between 30 and 30000),
  result_text text not null check (char_length(result_text) between 30 and 30000),
  model_name text not null check (char_length(model_name) between 1 and 80),
  model_version text check (model_version is null or char_length(model_version) <= 120),
  source_notes text check (source_notes is null or char_length(source_notes) <= 5000),
  status text not null default 'pending' check (status in ('pending','published','archived','rejected')),
  moderation_note text,
  review_scores jsonb,
  reviewed_by uuid references public.profiles(id) on delete set null,
  reviewed_at timestamptz,
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.submission_media (
  id uuid primary key default gen_random_uuid(),
  submission_id uuid not null references public.submissions(id) on delete cascade,
  author_id uuid not null references public.profiles(id) on delete cascade,
  kind text not null check (kind in ('image','video')),
  storage_bucket text not null check (storage_bucket in ('submission-inbox','published-media')),
  storage_path text not null,
  mime_type text not null check (mime_type in ('image/webp','video/webm')),
  bytes bigint not null check (bytes >= 0 and bytes <= 125829120),
  width integer check (width is null or width > 0),
  height integer check (height is null or height > 0),
  duration_seconds numeric check (duration_seconds is null or (duration_seconds >= 0 and duration_seconds <= 90.5)),
  alt_text text check (alt_text is null or char_length(alt_text) <= 300),
  sort_order integer not null default 0 check (sort_order between 0 and 20),
  created_at timestamptz not null default now(),
  unique(storage_bucket, storage_path)
);

create table if not exists public.moderation_events (
  id bigint generated by default as identity primary key,
  submission_id uuid not null references public.submissions(id) on delete cascade,
  moderator_id uuid references public.profiles(id) on delete set null,
  action text not null check (action in ('publish','archive','reject','restore','note')),
  note text,
  scores jsonb,
  created_at timestamptz not null default now()
);

-- Durable intake events make the hourly submission limit resistant to create/delete loops.
create table if not exists public.submission_intake_events (
  id bigint generated by default as identity primary key,
  author_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now()
);

create index if not exists submissions_status_published_idx on public.submissions(status, published_at desc);
create index if not exists submissions_author_idx on public.submissions(author_id, created_at desc);
create index if not exists submission_media_submission_idx on public.submission_media(submission_id, sort_order);
create index if not exists moderation_events_submission_idx on public.moderation_events(submission_id, created_at desc);
create index if not exists submission_intake_events_author_idx on public.submission_intake_events(author_id, created_at desc);

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_touch_updated_at on public.profiles;
create trigger profiles_touch_updated_at before update on public.profiles for each row execute function public.touch_updated_at();
drop trigger if exists submissions_touch_updated_at on public.submissions;
create trigger submissions_touch_updated_at before update on public.submissions for each row execute function public.touch_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles(id, display_name, role)
  values (
    new.id,
    case
      when char_length(trim(coalesce(new.raw_user_meta_data ->> 'display_name', ''))) >= 2
        then left(trim(new.raw_user_meta_data ->> 'display_name'), 40)
      when char_length(split_part(coalesce(new.email, ''), '@', 1)) >= 2
        then left(split_part(new.email, '@', 1), 40)
      else '회원'
    end,
    'user'
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();

create or replace function public.is_admin()
returns boolean
language sql
security definer
stable
set search_path = public
as $$
  select exists(select 1 from public.profiles where id = auth.uid() and role = 'admin');
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to anon, authenticated;

-- Basic anti-spam guard for direct inserts: max 5 new submissions per hour per account.
create or replace function public.guard_submission_rate()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  recent_count integer;
  v_display_name text;
begin
  if auth.uid() is null or new.author_id <> auth.uid() then
    raise exception '작성자 인증이 올바르지 않습니다.';
  end if;
  select display_name into v_display_name from public.profiles where id = auth.uid();
  if v_display_name is null then raise exception '프로필을 찾을 수 없습니다.'; end if;
  new.author_display_name := v_display_name;
  select count(*) into recent_count
  from public.submission_intake_events
  where author_id = auth.uid() and created_at > now() - interval '1 hour';
  if recent_count >= 5 then
    raise exception '한 시간에 최대 5건까지 제출할 수 있습니다.';
  end if;
  insert into public.submission_intake_events(author_id) values (auth.uid());
  return new;
end;
$$;

drop trigger if exists submissions_rate_guard on public.submissions;
create trigger submissions_rate_guard before insert on public.submissions for each row execute function public.guard_submission_rate();

alter table public.profiles enable row level security;
alter table public.submissions enable row level security;
alter table public.submission_media enable row level security;
alter table public.moderation_events enable row level security;
alter table public.submission_intake_events enable row level security;

-- Profiles contain roles, so only the owner/admin can read them. Public author names are snapshotted on submissions.
drop policy if exists "profiles readable" on public.profiles;
create policy "profiles readable" on public.profiles for select to authenticated using (id = auth.uid() or public.is_admin());
drop policy if exists "profile owner update" on public.profiles;
create policy "profile owner update" on public.profiles for update to authenticated using (id = auth.uid()) with check (id = auth.uid() and role = 'user');
drop policy if exists "admin profile update" on public.profiles;
create policy "admin profile update" on public.profiles for update to authenticated using (public.is_admin()) with check (public.is_admin());

-- Submissions: public sees only published. Owners see their own. Admin sees all.
drop policy if exists "published or owner submissions readable" on public.submissions;
create policy "published or owner submissions readable" on public.submissions for select to anon, authenticated using (
  status = 'published' or author_id = auth.uid() or public.is_admin()
);
drop policy if exists "users insert own pending submissions" on public.submissions;
create policy "users insert own pending submissions" on public.submissions for insert to authenticated with check (
  author_id = auth.uid() and status = 'pending'
);
drop policy if exists "users delete own pending submissions" on public.submissions;
create policy "users delete own pending submissions" on public.submissions for delete to authenticated using (
  author_id = auth.uid() and status = 'pending'
);
-- Users do not update moderation fields. Admin changes happen through the Edge Function with service role.

-- Media metadata follows submission visibility.
drop policy if exists "media readable with submission" on public.submission_media;
create policy "media readable with submission" on public.submission_media for select to anon, authenticated using (
  exists (
    select 1 from public.submissions s
    where s.id = submission_id and (s.status = 'published' or s.author_id = auth.uid() or public.is_admin())
  )
);
drop policy if exists "users insert own media" on public.submission_media;
create policy "users insert own media" on public.submission_media for insert to authenticated with check (
  author_id = auth.uid()
  and storage_bucket = 'submission-inbox'
  and exists(select 1 from public.submissions s where s.id = submission_id and s.author_id = auth.uid() and s.status = 'pending')
);
drop policy if exists "users delete own pending media" on public.submission_media;
create policy "users delete own pending media" on public.submission_media for delete to authenticated using (
  author_id = auth.uid()
  and storage_bucket = 'submission-inbox'
  and exists(select 1 from public.submissions s where s.id = submission_id and s.author_id = auth.uid() and s.status = 'pending')
);

-- Intake events are intentionally not exposed through client RLS. The SECURITY DEFINER trigger writes them.

-- Audit events are admin-only.
drop policy if exists "admins read moderation events" on public.moderation_events;
create policy "admins read moderation events" on public.moderation_events for select to authenticated using (public.is_admin());

-- Storage buckets. Originals are never accepted: only WebP/WebM.
insert into storage.buckets(id, name, public, file_size_limit, allowed_mime_types)
values ('submission-inbox', 'submission-inbox', false, 125829120, array['image/webp','video/webm'])
on conflict (id) do update set public=false, file_size_limit=excluded.file_size_limit, allowed_mime_types=excluded.allowed_mime_types;

insert into storage.buckets(id, name, public, file_size_limit, allowed_mime_types)
values ('published-media', 'published-media', true, 125829120, array['image/webp','video/webm'])
on conflict (id) do update set public=true, file_size_limit=excluded.file_size_limit, allowed_mime_types=excluded.allowed_mime_types;

-- submission-inbox: users can upload/read/remove only their own top-level UID folder; admins can review all.
drop policy if exists "user upload own inbox media" on storage.objects;
create policy "user upload own inbox media" on storage.objects for insert to authenticated with check (
  bucket_id = 'submission-inbox' and (storage.foldername(name))[1] = auth.uid()::text
);
drop policy if exists "user read own or admin inbox media" on storage.objects;
create policy "user read own or admin inbox media" on storage.objects for select to authenticated using (
  bucket_id = 'submission-inbox' and ((storage.foldername(name))[1] = auth.uid()::text or public.is_admin())
);
drop policy if exists "user delete own inbox media" on storage.objects;
create policy "user delete own inbox media" on storage.objects for delete to authenticated using (
  bucket_id = 'submission-inbox' and (storage.foldername(name))[1] = auth.uid()::text
);
-- published-media is public-read because the bucket is public. Browser users cannot insert/update/delete it.

-- Grants for PostgREST. RLS still applies.
grant usage on schema public to anon, authenticated, service_role;
grant select on public.profiles to authenticated;
grant select on public.submissions, public.submission_media to anon, authenticated;
grant insert, delete on public.submissions, public.submission_media to authenticated;
grant select on public.moderation_events to authenticated;

-- Secret-key/admin clients bypass RLS but still need SQL privileges.
grant all on public.profiles, public.submissions, public.submission_media, public.moderation_events, public.submission_intake_events to service_role;
grant usage, select on all sequences in schema public to service_role;

-- One-time administrator promotion after creating the account in Authentication > Users:
-- update public.profiles set role = 'admin' where id = (select id from auth.users where email = 'ADMIN_EMAIL');
