// Browser-safe local defaults. Production dist/config.js is generated by scripts/build.mjs.
window.__LLM_BIBLE_CONFIG__ = Object.freeze({
  supabaseUrl: '',
  supabasePublishableKey: '',
  siteUrl: window.location.origin + window.location.pathname.replace(/index\.html$/, '').replace(/\/$/, ''),
  repoName: 'llm-bible-community'
});
