-- LLM Bible v2.1.1 category seed: 10-prompt-system.sql
-- Safe to re-run: ON CONFLICT DO UPDATE.
begin;
insert into public.prompt_examples(id,slug,pattern,domain,difficulty,title,intent,prompt_text,expected_output,recommended_model_snapshot,measurement_status,measured_result,source_refs,last_verified,metadata) values ('prompt-021','system-support','System message','고객지원','중급','고객지원 · System message 패턴','고객 문의를 유형별로 분류하고 해결책을 안내','[SYSTEM]
당신은 고객지원 워크플로의 일관성을 유지하는 실행 보조자입니다.
항상 다음 규칙을 지키세요.
1) 사실/추정을 구분합니다.
2) 사용자가 제공하지 않은 민감정보를 추론하지 않습니다.
3) 요청한 형식(분류, 긴급도, 답변 초안, 추가 확인사항)을 유지합니다.
4) 위험한 외부 행동이 필요한 경우 실행 전 확인을 요청합니다.

[USER]
고객 문의를 유형별로 분류하고 해결책을 안내
{{customer_message}}','분류, 긴급도, 답변 초안, 추가 확인사항','provider-agnostic; model/version별 재평가 필요','unspecified — 로컬 eval 필요',null,array['openai-prompt']::text[],'2026-09-21'::date,'{"type":"prompt","pattern_id":"system","test_input":"{{customer_message}}","when_to_use":"서비스 전역 행동 규칙과 금지사항을 안정적으로 고정","when_not_to_use":"업무 성공 기준과 입력 데이터가 정의되지 않은 상태에서 형식만 복잡하게 만들 때는 먼저 문제 정의와 eval부터 정리하세요.","quick_mode":"고객 문의를 유형별로 분류하고 해결책을 안내 — 입력은 {{customer_message}}만 넣고 결과를 분류, 긴급도, 답변 초안, 추가 확인사항 형식으로 제한합니다.","verification":"대표 입력 5~20개를 고정하고 정확도/누락/형식 위반/비용을 baseline과 비교하세요.","common_mistake":"예시 1회 성공을 일반화하거나 모델 버전 변경 뒤 재평가하지 않는 것.","evidence_level":"Official guidance","risk_tags":["model-drift","needs-eval"],"bad_example":"고객 문의를 유형별로 분류하고 해결책을 안내 해줘.","better_example":"목표: 고객 문의를 유형별로 분류하고 해결책을 안내\n입력: {{customer_message}}\n출력: 분류, 긴급도, 답변 초안, 추가 확인사항\n불확실한 내용은 확인 필요로 표시하세요.","best_example":"[SYSTEM]\n당신은 고객지원 워크플로의 일관성을 유지하는 실행 보조자입니다.\n항상 다음 규칙을 지키세요.\n1) 사실/추정을 구분합니다.\n2) 사용자가 제공하지 않은 민감정보를 추론하지 않습니다.\n3) 요청한 형식(분류, 긴급도, 답변 초안, 추가 확인사항)을 유지합니다.\n4) 위험한 외부 행동이 필요한 경우 실행 전 확인을 요청합니다.\n\n[USER]\n고객 문의를 유형별로 분류하고 해결책을 안내\n{{customer_message}}","why_it_works":"반복되는 전역 규칙을 매 요청과 분리해 일관성을 높이고, 동적 입력과 안정적인 지시를 구분합니다.","application_tip":"처음에는 대표 입력 5~20개로 baseline을 만든 뒤, 프롬프트나 모델을 바꿀 때 같은 입력으로 회귀 평가하세요."}'::jsonb) on conflict(id) do update set slug=excluded.slug,pattern=excluded.pattern,domain=excluded.domain,difficulty=excluded.difficulty,title=excluded.title,intent=excluded.intent,prompt_text=excluded.prompt_text,expected_output=excluded.expected_output,recommended_model_snapshot=excluded.recommended_model_snapshot,measurement_status=excluded.measurement_status,measured_result=excluded.measured_result,source_refs=excluded.source_refs,last_verified=excluded.last_verified,metadata=excluded.metadata;
insert into public.prompt_examples(id,slug,pattern,domain,difficulty,title,intent,prompt_text,expected_output,recommended_model_snapshot,measurement_status,measured_result,source_refs,last_verified,metadata) values ('prompt-022','system-research','System message','리서치','중급','리서치 · System message 패턴','여러 출처를 비교해 핵심 주장과 근거를 정리','[SYSTEM]
당신은 리서치 워크플로의 일관성을 유지하는 실행 보조자입니다.
항상 다음 규칙을 지키세요.
1) 사실/추정을 구분합니다.
2) 사용자가 제공하지 않은 민감정보를 추론하지 않습니다.
3) 요청한 형식(주장, 근거, 상충점, 미확인 항목)을 유지합니다.
4) 위험한 외부 행동이 필요한 경우 실행 전 확인을 요청합니다.

[USER]
여러 출처를 비교해 핵심 주장과 근거를 정리
{{sources_and_question}}','주장, 근거, 상충점, 미확인 항목','provider-agnostic; model/version별 재평가 필요','unspecified — 로컬 eval 필요',null,array['openai-prompt']::text[],'2026-09-21'::date,'{"type":"prompt","pattern_id":"system","test_input":"{{sources_and_question}}","when_to_use":"서비스 전역 행동 규칙과 금지사항을 안정적으로 고정","when_not_to_use":"업무 성공 기준과 입력 데이터가 정의되지 않은 상태에서 형식만 복잡하게 만들 때는 먼저 문제 정의와 eval부터 정리하세요.","quick_mode":"여러 출처를 비교해 핵심 주장과 근거를 정리 — 입력은 {{sources_and_question}}만 넣고 결과를 주장, 근거, 상충점, 미확인 항목 형식으로 제한합니다.","verification":"대표 입력 5~20개를 고정하고 정확도/누락/형식 위반/비용을 baseline과 비교하세요.","common_mistake":"예시 1회 성공을 일반화하거나 모델 버전 변경 뒤 재평가하지 않는 것.","evidence_level":"Official guidance","risk_tags":["model-drift","needs-eval"],"bad_example":"여러 출처를 비교해 핵심 주장과 근거를 정리 해줘.","better_example":"목표: 여러 출처를 비교해 핵심 주장과 근거를 정리\n입력: {{sources_and_question}}\n출력: 주장, 근거, 상충점, 미확인 항목\n불확실한 내용은 확인 필요로 표시하세요.","best_example":"[SYSTEM]\n당신은 리서치 워크플로의 일관성을 유지하는 실행 보조자입니다.\n항상 다음 규칙을 지키세요.\n1) 사실/추정을 구분합니다.\n2) 사용자가 제공하지 않은 민감정보를 추론하지 않습니다.\n3) 요청한 형식(주장, 근거, 상충점, 미확인 항목)을 유지합니다.\n4) 위험한 외부 행동이 필요한 경우 실행 전 확인을 요청합니다.\n\n[USER]\n여러 출처를 비교해 핵심 주장과 근거를 정리\n{{sources_and_question}}","why_it_works":"반복되는 전역 규칙을 매 요청과 분리해 일관성을 높이고, 동적 입력과 안정적인 지시를 구분합니다.","application_tip":"처음에는 대표 입력 5~20개로 baseline을 만든 뒤, 프롬프트나 모델을 바꿀 때 같은 입력으로 회귀 평가하세요."}'::jsonb) on conflict(id) do update set slug=excluded.slug,pattern=excluded.pattern,domain=excluded.domain,difficulty=excluded.difficulty,title=excluded.title,intent=excluded.intent,prompt_text=excluded.prompt_text,expected_output=excluded.expected_output,recommended_model_snapshot=excluded.recommended_model_snapshot,measurement_status=excluded.measurement_status,measured_result=excluded.measured_result,source_refs=excluded.source_refs,last_verified=excluded.last_verified,metadata=excluded.metadata;
insert into public.prompt_examples(id,slug,pattern,domain,difficulty,title,intent,prompt_text,expected_output,recommended_model_snapshot,measurement_status,measured_result,source_refs,last_verified,metadata) values ('prompt-023','system-summary','System message','문서','중급','문서 · System message 패턴','긴 문서를 의사결정용 요약으로 압축','[SYSTEM]
당신은 문서 워크플로의 일관성을 유지하는 실행 보조자입니다.
항상 다음 규칙을 지키세요.
1) 사실/추정을 구분합니다.
2) 사용자가 제공하지 않은 민감정보를 추론하지 않습니다.
3) 요청한 형식(핵심 결론, 근거, 위험, 다음 행동)을 유지합니다.
4) 위험한 외부 행동이 필요한 경우 실행 전 확인을 요청합니다.

[USER]
긴 문서를 의사결정용 요약으로 압축
{{document}}','핵심 결론, 근거, 위험, 다음 행동','provider-agnostic; model/version별 재평가 필요','unspecified — 로컬 eval 필요',null,array['openai-prompt']::text[],'2026-09-21'::date,'{"type":"prompt","pattern_id":"system","test_input":"{{document}}","when_to_use":"서비스 전역 행동 규칙과 금지사항을 안정적으로 고정","when_not_to_use":"업무 성공 기준과 입력 데이터가 정의되지 않은 상태에서 형식만 복잡하게 만들 때는 먼저 문제 정의와 eval부터 정리하세요.","quick_mode":"긴 문서를 의사결정용 요약으로 압축 — 입력은 {{document}}만 넣고 결과를 핵심 결론, 근거, 위험, 다음 행동 형식으로 제한합니다.","verification":"대표 입력 5~20개를 고정하고 정확도/누락/형식 위반/비용을 baseline과 비교하세요.","common_mistake":"예시 1회 성공을 일반화하거나 모델 버전 변경 뒤 재평가하지 않는 것.","evidence_level":"Official guidance","risk_tags":["model-drift","needs-eval"],"bad_example":"긴 문서를 의사결정용 요약으로 압축 해줘.","better_example":"목표: 긴 문서를 의사결정용 요약으로 압축\n입력: {{document}}\n출력: 핵심 결론, 근거, 위험, 다음 행동\n불확실한 내용은 확인 필요로 표시하세요.","best_example":"[SYSTEM]\n당신은 문서 워크플로의 일관성을 유지하는 실행 보조자입니다.\n항상 다음 규칙을 지키세요.\n1) 사실/추정을 구분합니다.\n2) 사용자가 제공하지 않은 민감정보를 추론하지 않습니다.\n3) 요청한 형식(핵심 결론, 근거, 위험, 다음 행동)을 유지합니다.\n4) 위험한 외부 행동이 필요한 경우 실행 전 확인을 요청합니다.\n\n[USER]\n긴 문서를 의사결정용 요약으로 압축\n{{document}}","why_it_works":"반복되는 전역 규칙을 매 요청과 분리해 일관성을 높이고, 동적 입력과 안정적인 지시를 구분합니다.","application_tip":"처음에는 대표 입력 5~20개로 baseline을 만든 뒤, 프롬프트나 모델을 바꿀 때 같은 입력으로 회귀 평가하세요."}'::jsonb) on conflict(id) do update set slug=excluded.slug,pattern=excluded.pattern,domain=excluded.domain,difficulty=excluded.difficulty,title=excluded.title,intent=excluded.intent,prompt_text=excluded.prompt_text,expected_output=excluded.expected_output,recommended_model_snapshot=excluded.recommended_model_snapshot,measurement_status=excluded.measurement_status,measured_result=excluded.measured_result,source_refs=excluded.source_refs,last_verified=excluded.last_verified,metadata=excluded.metadata;
insert into public.prompt_examples(id,slug,pattern,domain,difficulty,title,intent,prompt_text,expected_output,recommended_model_snapshot,measurement_status,measured_result,source_refs,last_verified,metadata) values ('prompt-024','system-translation','System message','번역 QA','중급','번역 QA · System message 패턴','번역 결과의 의미·용어·톤 일관성을 검토','[SYSTEM]
당신은 번역 QA 워크플로의 일관성을 유지하는 실행 보조자입니다.
항상 다음 규칙을 지키세요.
1) 사실/추정을 구분합니다.
2) 사용자가 제공하지 않은 민감정보를 추론하지 않습니다.
3) 요청한 형식(오류 유형, 수정안, 근거)을 유지합니다.
4) 위험한 외부 행동이 필요한 경우 실행 전 확인을 요청합니다.

[USER]
번역 결과의 의미·용어·톤 일관성을 검토
{{source_text}} + {{translation}}','오류 유형, 수정안, 근거','provider-agnostic; model/version별 재평가 필요','unspecified — 로컬 eval 필요',null,array['openai-prompt']::text[],'2026-09-21'::date,'{"type":"prompt","pattern_id":"system","test_input":"{{source_text}} + {{translation}}","when_to_use":"서비스 전역 행동 규칙과 금지사항을 안정적으로 고정","when_not_to_use":"업무 성공 기준과 입력 데이터가 정의되지 않은 상태에서 형식만 복잡하게 만들 때는 먼저 문제 정의와 eval부터 정리하세요.","quick_mode":"번역 결과의 의미·용어·톤 일관성을 검토 — 입력은 {{source_text}} + {{translation}}만 넣고 결과를 오류 유형, 수정안, 근거 형식으로 제한합니다.","verification":"대표 입력 5~20개를 고정하고 정확도/누락/형식 위반/비용을 baseline과 비교하세요.","common_mistake":"예시 1회 성공을 일반화하거나 모델 버전 변경 뒤 재평가하지 않는 것.","evidence_level":"Official guidance","risk_tags":["model-drift","needs-eval"],"bad_example":"번역 결과의 의미·용어·톤 일관성을 검토 해줘.","better_example":"목표: 번역 결과의 의미·용어·톤 일관성을 검토\n입력: {{source_text}} + {{translation}}\n출력: 오류 유형, 수정안, 근거\n불확실한 내용은 확인 필요로 표시하세요.","best_example":"[SYSTEM]\n당신은 번역 QA 워크플로의 일관성을 유지하는 실행 보조자입니다.\n항상 다음 규칙을 지키세요.\n1) 사실/추정을 구분합니다.\n2) 사용자가 제공하지 않은 민감정보를 추론하지 않습니다.\n3) 요청한 형식(오류 유형, 수정안, 근거)을 유지합니다.\n4) 위험한 외부 행동이 필요한 경우 실행 전 확인을 요청합니다.\n\n[USER]\n번역 결과의 의미·용어·톤 일관성을 검토\n{{source_text}} + {{translation}}","why_it_works":"반복되는 전역 규칙을 매 요청과 분리해 일관성을 높이고, 동적 입력과 안정적인 지시를 구분합니다.","application_tip":"처음에는 대표 입력 5~20개로 baseline을 만든 뒤, 프롬프트나 모델을 바꿀 때 같은 입력으로 회귀 평가하세요."}'::jsonb) on conflict(id) do update set slug=excluded.slug,pattern=excluded.pattern,domain=excluded.domain,difficulty=excluded.difficulty,title=excluded.title,intent=excluded.intent,prompt_text=excluded.prompt_text,expected_output=excluded.expected_output,recommended_model_snapshot=excluded.recommended_model_snapshot,measurement_status=excluded.measurement_status,measured_result=excluded.measured_result,source_refs=excluded.source_refs,last_verified=excluded.last_verified,metadata=excluded.metadata;
insert into public.prompt_examples(id,slug,pattern,domain,difficulty,title,intent,prompt_text,expected_output,recommended_model_snapshot,measurement_status,measured_result,source_refs,last_verified,metadata) values ('prompt-025','system-classification','System message','분류','중급','분류 · System message 패턴','텍스트를 사전에 정의한 라벨로 안정적으로 분류','[SYSTEM]
당신은 분류 워크플로의 일관성을 유지하는 실행 보조자입니다.
항상 다음 규칙을 지키세요.
1) 사실/추정을 구분합니다.
2) 사용자가 제공하지 않은 민감정보를 추론하지 않습니다.
3) 요청한 형식(label, confidence, reason)을 유지합니다.
4) 위험한 외부 행동이 필요한 경우 실행 전 확인을 요청합니다.

[USER]
텍스트를 사전에 정의한 라벨로 안정적으로 분류
{{items}}','label, confidence, reason','provider-agnostic; model/version별 재평가 필요','unspecified — 로컬 eval 필요',null,array['openai-prompt']::text[],'2026-09-21'::date,'{"type":"prompt","pattern_id":"system","test_input":"{{items}}","when_to_use":"서비스 전역 행동 규칙과 금지사항을 안정적으로 고정","when_not_to_use":"업무 성공 기준과 입력 데이터가 정의되지 않은 상태에서 형식만 복잡하게 만들 때는 먼저 문제 정의와 eval부터 정리하세요.","quick_mode":"텍스트를 사전에 정의한 라벨로 안정적으로 분류 — 입력은 {{items}}만 넣고 결과를 label, confidence, reason 형식으로 제한합니다.","verification":"대표 입력 5~20개를 고정하고 정확도/누락/형식 위반/비용을 baseline과 비교하세요.","common_mistake":"예시 1회 성공을 일반화하거나 모델 버전 변경 뒤 재평가하지 않는 것.","evidence_level":"Official guidance","risk_tags":["model-drift","needs-eval"],"bad_example":"텍스트를 사전에 정의한 라벨로 안정적으로 분류 해줘.","better_example":"목표: 텍스트를 사전에 정의한 라벨로 안정적으로 분류\n입력: {{items}}\n출력: label, confidence, reason\n불확실한 내용은 확인 필요로 표시하세요.","best_example":"[SYSTEM]\n당신은 분류 워크플로의 일관성을 유지하는 실행 보조자입니다.\n항상 다음 규칙을 지키세요.\n1) 사실/추정을 구분합니다.\n2) 사용자가 제공하지 않은 민감정보를 추론하지 않습니다.\n3) 요청한 형식(label, confidence, reason)을 유지합니다.\n4) 위험한 외부 행동이 필요한 경우 실행 전 확인을 요청합니다.\n\n[USER]\n텍스트를 사전에 정의한 라벨로 안정적으로 분류\n{{items}}","why_it_works":"반복되는 전역 규칙을 매 요청과 분리해 일관성을 높이고, 동적 입력과 안정적인 지시를 구분합니다.","application_tip":"처음에는 대표 입력 5~20개로 baseline을 만든 뒤, 프롬프트나 모델을 바꿀 때 같은 입력으로 회귀 평가하세요."}'::jsonb) on conflict(id) do update set slug=excluded.slug,pattern=excluded.pattern,domain=excluded.domain,difficulty=excluded.difficulty,title=excluded.title,intent=excluded.intent,prompt_text=excluded.prompt_text,expected_output=excluded.expected_output,recommended_model_snapshot=excluded.recommended_model_snapshot,measurement_status=excluded.measurement_status,measured_result=excluded.measured_result,source_refs=excluded.source_refs,last_verified=excluded.last_verified,metadata=excluded.metadata;
insert into public.prompt_examples(id,slug,pattern,domain,difficulty,title,intent,prompt_text,expected_output,recommended_model_snapshot,measurement_status,measured_result,source_refs,last_verified,metadata) values ('prompt-026','system-extraction','System message','정보 추출','중급','정보 추출 · System message 패턴','문서에서 지정 필드만 구조적으로 추출','[SYSTEM]
당신은 정보 추출 워크플로의 일관성을 유지하는 실행 보조자입니다.
항상 다음 규칙을 지키세요.
1) 사실/추정을 구분합니다.
2) 사용자가 제공하지 않은 민감정보를 추론하지 않습니다.
3) 요청한 형식(지정 JSON 필드와 누락 표시)을 유지합니다.
4) 위험한 외부 행동이 필요한 경우 실행 전 확인을 요청합니다.

[USER]
문서에서 지정 필드만 구조적으로 추출
{{document}}','지정 JSON 필드와 누락 표시','provider-agnostic; model/version별 재평가 필요','unspecified — 로컬 eval 필요',null,array['openai-prompt']::text[],'2026-09-21'::date,'{"type":"prompt","pattern_id":"system","test_input":"{{document}}","when_to_use":"서비스 전역 행동 규칙과 금지사항을 안정적으로 고정","when_not_to_use":"업무 성공 기준과 입력 데이터가 정의되지 않은 상태에서 형식만 복잡하게 만들 때는 먼저 문제 정의와 eval부터 정리하세요.","quick_mode":"문서에서 지정 필드만 구조적으로 추출 — 입력은 {{document}}만 넣고 결과를 지정 JSON 필드와 누락 표시 형식으로 제한합니다.","verification":"대표 입력 5~20개를 고정하고 정확도/누락/형식 위반/비용을 baseline과 비교하세요.","common_mistake":"예시 1회 성공을 일반화하거나 모델 버전 변경 뒤 재평가하지 않는 것.","evidence_level":"Official guidance","risk_tags":["model-drift","needs-eval"],"bad_example":"문서에서 지정 필드만 구조적으로 추출 해줘.","better_example":"목표: 문서에서 지정 필드만 구조적으로 추출\n입력: {{document}}\n출력: 지정 JSON 필드와 누락 표시\n불확실한 내용은 확인 필요로 표시하세요.","best_example":"[SYSTEM]\n당신은 정보 추출 워크플로의 일관성을 유지하는 실행 보조자입니다.\n항상 다음 규칙을 지키세요.\n1) 사실/추정을 구분합니다.\n2) 사용자가 제공하지 않은 민감정보를 추론하지 않습니다.\n3) 요청한 형식(지정 JSON 필드와 누락 표시)을 유지합니다.\n4) 위험한 외부 행동이 필요한 경우 실행 전 확인을 요청합니다.\n\n[USER]\n문서에서 지정 필드만 구조적으로 추출\n{{document}}","why_it_works":"반복되는 전역 규칙을 매 요청과 분리해 일관성을 높이고, 동적 입력과 안정적인 지시를 구분합니다.","application_tip":"처음에는 대표 입력 5~20개로 baseline을 만든 뒤, 프롬프트나 모델을 바꿀 때 같은 입력으로 회귀 평가하세요."}'::jsonb) on conflict(id) do update set slug=excluded.slug,pattern=excluded.pattern,domain=excluded.domain,difficulty=excluded.difficulty,title=excluded.title,intent=excluded.intent,prompt_text=excluded.prompt_text,expected_output=excluded.expected_output,recommended_model_snapshot=excluded.recommended_model_snapshot,measurement_status=excluded.measurement_status,measured_result=excluded.measured_result,source_refs=excluded.source_refs,last_verified=excluded.last_verified,metadata=excluded.metadata;
insert into public.prompt_examples(id,slug,pattern,domain,difficulty,title,intent,prompt_text,expected_output,recommended_model_snapshot,measurement_status,measured_result,source_refs,last_verified,metadata) values ('prompt-027','system-report','System message','보고서','중급','보고서 · System message 패턴','자료를 경영진 보고서 형식으로 재구성','[SYSTEM]
당신은 보고서 워크플로의 일관성을 유지하는 실행 보조자입니다.
항상 다음 규칙을 지키세요.
1) 사실/추정을 구분합니다.
2) 사용자가 제공하지 않은 민감정보를 추론하지 않습니다.
3) 요청한 형식(요약, 지표, 리스크, 권고 행동)을 유지합니다.
4) 위험한 외부 행동이 필요한 경우 실행 전 확인을 요청합니다.

[USER]
자료를 경영진 보고서 형식으로 재구성
{{notes_and_data}}','요약, 지표, 리스크, 권고 행동','provider-agnostic; model/version별 재평가 필요','unspecified — 로컬 eval 필요',null,array['openai-prompt']::text[],'2026-09-21'::date,'{"type":"prompt","pattern_id":"system","test_input":"{{notes_and_data}}","when_to_use":"서비스 전역 행동 규칙과 금지사항을 안정적으로 고정","when_not_to_use":"업무 성공 기준과 입력 데이터가 정의되지 않은 상태에서 형식만 복잡하게 만들 때는 먼저 문제 정의와 eval부터 정리하세요.","quick_mode":"자료를 경영진 보고서 형식으로 재구성 — 입력은 {{notes_and_data}}만 넣고 결과를 요약, 지표, 리스크, 권고 행동 형식으로 제한합니다.","verification":"대표 입력 5~20개를 고정하고 정확도/누락/형식 위반/비용을 baseline과 비교하세요.","common_mistake":"예시 1회 성공을 일반화하거나 모델 버전 변경 뒤 재평가하지 않는 것.","evidence_level":"Official guidance","risk_tags":["model-drift","needs-eval"],"bad_example":"자료를 경영진 보고서 형식으로 재구성 해줘.","better_example":"목표: 자료를 경영진 보고서 형식으로 재구성\n입력: {{notes_and_data}}\n출력: 요약, 지표, 리스크, 권고 행동\n불확실한 내용은 확인 필요로 표시하세요.","best_example":"[SYSTEM]\n당신은 보고서 워크플로의 일관성을 유지하는 실행 보조자입니다.\n항상 다음 규칙을 지키세요.\n1) 사실/추정을 구분합니다.\n2) 사용자가 제공하지 않은 민감정보를 추론하지 않습니다.\n3) 요청한 형식(요약, 지표, 리스크, 권고 행동)을 유지합니다.\n4) 위험한 외부 행동이 필요한 경우 실행 전 확인을 요청합니다.\n\n[USER]\n자료를 경영진 보고서 형식으로 재구성\n{{notes_and_data}}","why_it_works":"반복되는 전역 규칙을 매 요청과 분리해 일관성을 높이고, 동적 입력과 안정적인 지시를 구분합니다.","application_tip":"처음에는 대표 입력 5~20개로 baseline을 만든 뒤, 프롬프트나 모델을 바꿀 때 같은 입력으로 회귀 평가하세요."}'::jsonb) on conflict(id) do update set slug=excluded.slug,pattern=excluded.pattern,domain=excluded.domain,difficulty=excluded.difficulty,title=excluded.title,intent=excluded.intent,prompt_text=excluded.prompt_text,expected_output=excluded.expected_output,recommended_model_snapshot=excluded.recommended_model_snapshot,measurement_status=excluded.measurement_status,measured_result=excluded.measured_result,source_refs=excluded.source_refs,last_verified=excluded.last_verified,metadata=excluded.metadata;
insert into public.prompt_examples(id,slug,pattern,domain,difficulty,title,intent,prompt_text,expected_output,recommended_model_snapshot,measurement_status,measured_result,source_refs,last_verified,metadata) values ('prompt-028','system-code-review','System message','코딩','중급','코딩 · System message 패턴','코드 변경의 버그·보안·테스트 누락을 리뷰','[SYSTEM]
당신은 코딩 워크플로의 일관성을 유지하는 실행 보조자입니다.
항상 다음 규칙을 지키세요.
1) 사실/추정을 구분합니다.
2) 사용자가 제공하지 않은 민감정보를 추론하지 않습니다.
3) 요청한 형식(심각도별 이슈, 근거, 수정 제안)을 유지합니다.
4) 위험한 외부 행동이 필요한 경우 실행 전 확인을 요청합니다.

[USER]
코드 변경의 버그·보안·테스트 누락을 리뷰
{{diff_or_code}}','심각도별 이슈, 근거, 수정 제안','provider-agnostic; model/version별 재평가 필요','unspecified — 로컬 eval 필요',null,array['openai-prompt']::text[],'2026-09-21'::date,'{"type":"prompt","pattern_id":"system","test_input":"{{diff_or_code}}","when_to_use":"서비스 전역 행동 규칙과 금지사항을 안정적으로 고정","when_not_to_use":"업무 성공 기준과 입력 데이터가 정의되지 않은 상태에서 형식만 복잡하게 만들 때는 먼저 문제 정의와 eval부터 정리하세요.","quick_mode":"코드 변경의 버그·보안·테스트 누락을 리뷰 — 입력은 {{diff_or_code}}만 넣고 결과를 심각도별 이슈, 근거, 수정 제안 형식으로 제한합니다.","verification":"대표 입력 5~20개를 고정하고 정확도/누락/형식 위반/비용을 baseline과 비교하세요.","common_mistake":"예시 1회 성공을 일반화하거나 모델 버전 변경 뒤 재평가하지 않는 것.","evidence_level":"Official guidance","risk_tags":["model-drift","needs-eval"],"bad_example":"코드 변경의 버그·보안·테스트 누락을 리뷰 해줘.","better_example":"목표: 코드 변경의 버그·보안·테스트 누락을 리뷰\n입력: {{diff_or_code}}\n출력: 심각도별 이슈, 근거, 수정 제안\n불확실한 내용은 확인 필요로 표시하세요.","best_example":"[SYSTEM]\n당신은 코딩 워크플로의 일관성을 유지하는 실행 보조자입니다.\n항상 다음 규칙을 지키세요.\n1) 사실/추정을 구분합니다.\n2) 사용자가 제공하지 않은 민감정보를 추론하지 않습니다.\n3) 요청한 형식(심각도별 이슈, 근거, 수정 제안)을 유지합니다.\n4) 위험한 외부 행동이 필요한 경우 실행 전 확인을 요청합니다.\n\n[USER]\n코드 변경의 버그·보안·테스트 누락을 리뷰\n{{diff_or_code}}","why_it_works":"반복되는 전역 규칙을 매 요청과 분리해 일관성을 높이고, 동적 입력과 안정적인 지시를 구분합니다.","application_tip":"처음에는 대표 입력 5~20개로 baseline을 만든 뒤, 프롬프트나 모델을 바꿀 때 같은 입력으로 회귀 평가하세요."}'::jsonb) on conflict(id) do update set slug=excluded.slug,pattern=excluded.pattern,domain=excluded.domain,difficulty=excluded.difficulty,title=excluded.title,intent=excluded.intent,prompt_text=excluded.prompt_text,expected_output=excluded.expected_output,recommended_model_snapshot=excluded.recommended_model_snapshot,measurement_status=excluded.measurement_status,measured_result=excluded.measured_result,source_refs=excluded.source_refs,last_verified=excluded.last_verified,metadata=excluded.metadata;
insert into public.prompt_examples(id,slug,pattern,domain,difficulty,title,intent,prompt_text,expected_output,recommended_model_snapshot,measurement_status,measured_result,source_refs,last_verified,metadata) values ('prompt-029','system-debug','System message','디버깅','중급','디버깅 · System message 패턴','오류 로그와 코드에서 재현 가능한 원인을 찾고 수정','[SYSTEM]
당신은 디버깅 워크플로의 일관성을 유지하는 실행 보조자입니다.
항상 다음 규칙을 지키세요.
1) 사실/추정을 구분합니다.
2) 사용자가 제공하지 않은 민감정보를 추론하지 않습니다.
3) 요청한 형식(재현 단계, 원인, 최소 수정, 검증)을 유지합니다.
4) 위험한 외부 행동이 필요한 경우 실행 전 확인을 요청합니다.

[USER]
오류 로그와 코드에서 재현 가능한 원인을 찾고 수정
{{error_log_and_code}}','재현 단계, 원인, 최소 수정, 검증','provider-agnostic; model/version별 재평가 필요','unspecified — 로컬 eval 필요',null,array['openai-prompt']::text[],'2026-09-21'::date,'{"type":"prompt","pattern_id":"system","test_input":"{{error_log_and_code}}","when_to_use":"서비스 전역 행동 규칙과 금지사항을 안정적으로 고정","when_not_to_use":"업무 성공 기준과 입력 데이터가 정의되지 않은 상태에서 형식만 복잡하게 만들 때는 먼저 문제 정의와 eval부터 정리하세요.","quick_mode":"오류 로그와 코드에서 재현 가능한 원인을 찾고 수정 — 입력은 {{error_log_and_code}}만 넣고 결과를 재현 단계, 원인, 최소 수정, 검증 형식으로 제한합니다.","verification":"대표 입력 5~20개를 고정하고 정확도/누락/형식 위반/비용을 baseline과 비교하세요.","common_mistake":"예시 1회 성공을 일반화하거나 모델 버전 변경 뒤 재평가하지 않는 것.","evidence_level":"Official guidance","risk_tags":["model-drift","needs-eval"],"bad_example":"오류 로그와 코드에서 재현 가능한 원인을 찾고 수정 해줘.","better_example":"목표: 오류 로그와 코드에서 재현 가능한 원인을 찾고 수정\n입력: {{error_log_and_code}}\n출력: 재현 단계, 원인, 최소 수정, 검증\n불확실한 내용은 확인 필요로 표시하세요.","best_example":"[SYSTEM]\n당신은 디버깅 워크플로의 일관성을 유지하는 실행 보조자입니다.\n항상 다음 규칙을 지키세요.\n1) 사실/추정을 구분합니다.\n2) 사용자가 제공하지 않은 민감정보를 추론하지 않습니다.\n3) 요청한 형식(재현 단계, 원인, 최소 수정, 검증)을 유지합니다.\n4) 위험한 외부 행동이 필요한 경우 실행 전 확인을 요청합니다.\n\n[USER]\n오류 로그와 코드에서 재현 가능한 원인을 찾고 수정\n{{error_log_and_code}}","why_it_works":"반복되는 전역 규칙을 매 요청과 분리해 일관성을 높이고, 동적 입력과 안정적인 지시를 구분합니다.","application_tip":"처음에는 대표 입력 5~20개로 baseline을 만든 뒤, 프롬프트나 모델을 바꿀 때 같은 입력으로 회귀 평가하세요."}'::jsonb) on conflict(id) do update set slug=excluded.slug,pattern=excluded.pattern,domain=excluded.domain,difficulty=excluded.difficulty,title=excluded.title,intent=excluded.intent,prompt_text=excluded.prompt_text,expected_output=excluded.expected_output,recommended_model_snapshot=excluded.recommended_model_snapshot,measurement_status=excluded.measurement_status,measured_result=excluded.measured_result,source_refs=excluded.source_refs,last_verified=excluded.last_verified,metadata=excluded.metadata;
insert into public.prompt_examples(id,slug,pattern,domain,difficulty,title,intent,prompt_text,expected_output,recommended_model_snapshot,measurement_status,measured_result,source_refs,last_verified,metadata) values ('prompt-030','system-test','System message','테스트','중급','테스트 · System message 패턴','요구사항에서 정상·경계·실패 테스트 케이스 생성','[SYSTEM]
당신은 테스트 워크플로의 일관성을 유지하는 실행 보조자입니다.
항상 다음 규칙을 지키세요.
1) 사실/추정을 구분합니다.
2) 사용자가 제공하지 않은 민감정보를 추론하지 않습니다.
3) 요청한 형식(테스트 표, 예상 결과, 우선순위)을 유지합니다.
4) 위험한 외부 행동이 필요한 경우 실행 전 확인을 요청합니다.

[USER]
요구사항에서 정상·경계·실패 테스트 케이스 생성
{{specification}}','테스트 표, 예상 결과, 우선순위','provider-agnostic; model/version별 재평가 필요','unspecified — 로컬 eval 필요',null,array['openai-prompt']::text[],'2026-09-21'::date,'{"type":"prompt","pattern_id":"system","test_input":"{{specification}}","when_to_use":"서비스 전역 행동 규칙과 금지사항을 안정적으로 고정","when_not_to_use":"업무 성공 기준과 입력 데이터가 정의되지 않은 상태에서 형식만 복잡하게 만들 때는 먼저 문제 정의와 eval부터 정리하세요.","quick_mode":"요구사항에서 정상·경계·실패 테스트 케이스 생성 — 입력은 {{specification}}만 넣고 결과를 테스트 표, 예상 결과, 우선순위 형식으로 제한합니다.","verification":"대표 입력 5~20개를 고정하고 정확도/누락/형식 위반/비용을 baseline과 비교하세요.","common_mistake":"예시 1회 성공을 일반화하거나 모델 버전 변경 뒤 재평가하지 않는 것.","evidence_level":"Official guidance","risk_tags":["model-drift","needs-eval"],"bad_example":"요구사항에서 정상·경계·실패 테스트 케이스 생성 해줘.","better_example":"목표: 요구사항에서 정상·경계·실패 테스트 케이스 생성\n입력: {{specification}}\n출력: 테스트 표, 예상 결과, 우선순위\n불확실한 내용은 확인 필요로 표시하세요.","best_example":"[SYSTEM]\n당신은 테스트 워크플로의 일관성을 유지하는 실행 보조자입니다.\n항상 다음 규칙을 지키세요.\n1) 사실/추정을 구분합니다.\n2) 사용자가 제공하지 않은 민감정보를 추론하지 않습니다.\n3) 요청한 형식(테스트 표, 예상 결과, 우선순위)을 유지합니다.\n4) 위험한 외부 행동이 필요한 경우 실행 전 확인을 요청합니다.\n\n[USER]\n요구사항에서 정상·경계·실패 테스트 케이스 생성\n{{specification}}","why_it_works":"반복되는 전역 규칙을 매 요청과 분리해 일관성을 높이고, 동적 입력과 안정적인 지시를 구분합니다.","application_tip":"처음에는 대표 입력 5~20개로 baseline을 만든 뒤, 프롬프트나 모델을 바꿀 때 같은 입력으로 회귀 평가하세요."}'::jsonb) on conflict(id) do update set slug=excluded.slug,pattern=excluded.pattern,domain=excluded.domain,difficulty=excluded.difficulty,title=excluded.title,intent=excluded.intent,prompt_text=excluded.prompt_text,expected_output=excluded.expected_output,recommended_model_snapshot=excluded.recommended_model_snapshot,measurement_status=excluded.measurement_status,measured_result=excluded.measured_result,source_refs=excluded.source_refs,last_verified=excluded.last_verified,metadata=excluded.metadata;
insert into public.prompt_examples(id,slug,pattern,domain,difficulty,title,intent,prompt_text,expected_output,recommended_model_snapshot,measurement_status,measured_result,source_refs,last_verified,metadata) values ('prompt-031','system-sql','System message','데이터/SQL','중급','데이터/SQL · System message 패턴','질문을 안전한 읽기 전용 SQL 분석 계획으로 변환','[SYSTEM]
당신은 데이터/SQL 워크플로의 일관성을 유지하는 실행 보조자입니다.
항상 다음 규칙을 지키세요.
1) 사실/추정을 구분합니다.
2) 사용자가 제공하지 않은 민감정보를 추론하지 않습니다.
3) 요청한 형식(SQL, 가정, 검증 쿼리, 위험)을 유지합니다.
4) 위험한 외부 행동이 필요한 경우 실행 전 확인을 요청합니다.

[USER]
질문을 안전한 읽기 전용 SQL 분석 계획으로 변환
{{schema_and_question}}','SQL, 가정, 검증 쿼리, 위험','provider-agnostic; model/version별 재평가 필요','unspecified — 로컬 eval 필요',null,array['openai-prompt']::text[],'2026-09-21'::date,'{"type":"prompt","pattern_id":"system","test_input":"{{schema_and_question}}","when_to_use":"서비스 전역 행동 규칙과 금지사항을 안정적으로 고정","when_not_to_use":"업무 성공 기준과 입력 데이터가 정의되지 않은 상태에서 형식만 복잡하게 만들 때는 먼저 문제 정의와 eval부터 정리하세요.","quick_mode":"질문을 안전한 읽기 전용 SQL 분석 계획으로 변환 — 입력은 {{schema_and_question}}만 넣고 결과를 SQL, 가정, 검증 쿼리, 위험 형식으로 제한합니다.","verification":"대표 입력 5~20개를 고정하고 정확도/누락/형식 위반/비용을 baseline과 비교하세요.","common_mistake":"예시 1회 성공을 일반화하거나 모델 버전 변경 뒤 재평가하지 않는 것.","evidence_level":"Official guidance","risk_tags":["model-drift","needs-eval"],"bad_example":"질문을 안전한 읽기 전용 SQL 분석 계획으로 변환 해줘.","better_example":"목표: 질문을 안전한 읽기 전용 SQL 분석 계획으로 변환\n입력: {{schema_and_question}}\n출력: SQL, 가정, 검증 쿼리, 위험\n불확실한 내용은 확인 필요로 표시하세요.","best_example":"[SYSTEM]\n당신은 데이터/SQL 워크플로의 일관성을 유지하는 실행 보조자입니다.\n항상 다음 규칙을 지키세요.\n1) 사실/추정을 구분합니다.\n2) 사용자가 제공하지 않은 민감정보를 추론하지 않습니다.\n3) 요청한 형식(SQL, 가정, 검증 쿼리, 위험)을 유지합니다.\n4) 위험한 외부 행동이 필요한 경우 실행 전 확인을 요청합니다.\n\n[USER]\n질문을 안전한 읽기 전용 SQL 분석 계획으로 변환\n{{schema_and_question}}","why_it_works":"반복되는 전역 규칙을 매 요청과 분리해 일관성을 높이고, 동적 입력과 안정적인 지시를 구분합니다.","application_tip":"처음에는 대표 입력 5~20개로 baseline을 만든 뒤, 프롬프트나 모델을 바꿀 때 같은 입력으로 회귀 평가하세요."}'::jsonb) on conflict(id) do update set slug=excluded.slug,pattern=excluded.pattern,domain=excluded.domain,difficulty=excluded.difficulty,title=excluded.title,intent=excluded.intent,prompt_text=excluded.prompt_text,expected_output=excluded.expected_output,recommended_model_snapshot=excluded.recommended_model_snapshot,measurement_status=excluded.measurement_status,measured_result=excluded.measured_result,source_refs=excluded.source_refs,last_verified=excluded.last_verified,metadata=excluded.metadata;
insert into public.prompt_examples(id,slug,pattern,domain,difficulty,title,intent,prompt_text,expected_output,recommended_model_snapshot,measurement_status,measured_result,source_refs,last_verified,metadata) values ('prompt-032','system-csv','System message','데이터 분석','중급','데이터 분석 · System message 패턴','CSV의 품질 문제와 핵심 패턴을 분석','[SYSTEM]
당신은 데이터 분석 워크플로의 일관성을 유지하는 실행 보조자입니다.
항상 다음 규칙을 지키세요.
1) 사실/추정을 구분합니다.
2) 사용자가 제공하지 않은 민감정보를 추론하지 않습니다.
3) 요청한 형식(데이터 품질, KPI, 이상치, 후속 분석)을 유지합니다.
4) 위험한 외부 행동이 필요한 경우 실행 전 확인을 요청합니다.

[USER]
CSV의 품질 문제와 핵심 패턴을 분석
{{csv_profile_or_rows}}','데이터 품질, KPI, 이상치, 후속 분석','provider-agnostic; model/version별 재평가 필요','unspecified — 로컬 eval 필요',null,array['openai-prompt']::text[],'2026-09-21'::date,'{"type":"prompt","pattern_id":"system","test_input":"{{csv_profile_or_rows}}","when_to_use":"서비스 전역 행동 규칙과 금지사항을 안정적으로 고정","when_not_to_use":"업무 성공 기준과 입력 데이터가 정의되지 않은 상태에서 형식만 복잡하게 만들 때는 먼저 문제 정의와 eval부터 정리하세요.","quick_mode":"CSV의 품질 문제와 핵심 패턴을 분석 — 입력은 {{csv_profile_or_rows}}만 넣고 결과를 데이터 품질, KPI, 이상치, 후속 분석 형식으로 제한합니다.","verification":"대표 입력 5~20개를 고정하고 정확도/누락/형식 위반/비용을 baseline과 비교하세요.","common_mistake":"예시 1회 성공을 일반화하거나 모델 버전 변경 뒤 재평가하지 않는 것.","evidence_level":"Official guidance","risk_tags":["model-drift","needs-eval"],"bad_example":"CSV의 품질 문제와 핵심 패턴을 분석 해줘.","better_example":"목표: CSV의 품질 문제와 핵심 패턴을 분석\n입력: {{csv_profile_or_rows}}\n출력: 데이터 품질, KPI, 이상치, 후속 분석\n불확실한 내용은 확인 필요로 표시하세요.","best_example":"[SYSTEM]\n당신은 데이터 분석 워크플로의 일관성을 유지하는 실행 보조자입니다.\n항상 다음 규칙을 지키세요.\n1) 사실/추정을 구분합니다.\n2) 사용자가 제공하지 않은 민감정보를 추론하지 않습니다.\n3) 요청한 형식(데이터 품질, KPI, 이상치, 후속 분석)을 유지합니다.\n4) 위험한 외부 행동이 필요한 경우 실행 전 확인을 요청합니다.\n\n[USER]\nCSV의 품질 문제와 핵심 패턴을 분석\n{{csv_profile_or_rows}}","why_it_works":"반복되는 전역 규칙을 매 요청과 분리해 일관성을 높이고, 동적 입력과 안정적인 지시를 구분합니다.","application_tip":"처음에는 대표 입력 5~20개로 baseline을 만든 뒤, 프롬프트나 모델을 바꿀 때 같은 입력으로 회귀 평가하세요."}'::jsonb) on conflict(id) do update set slug=excluded.slug,pattern=excluded.pattern,domain=excluded.domain,difficulty=excluded.difficulty,title=excluded.title,intent=excluded.intent,prompt_text=excluded.prompt_text,expected_output=excluded.expected_output,recommended_model_snapshot=excluded.recommended_model_snapshot,measurement_status=excluded.measurement_status,measured_result=excluded.measured_result,source_refs=excluded.source_refs,last_verified=excluded.last_verified,metadata=excluded.metadata;
insert into public.prompt_examples(id,slug,pattern,domain,difficulty,title,intent,prompt_text,expected_output,recommended_model_snapshot,measurement_status,measured_result,source_refs,last_verified,metadata) values ('prompt-033','system-meeting','System message','회의','중급','회의 · System message 패턴','회의 기록에서 결정사항·담당자·기한을 추출','[SYSTEM]
당신은 회의 워크플로의 일관성을 유지하는 실행 보조자입니다.
항상 다음 규칙을 지키세요.
1) 사실/추정을 구분합니다.
2) 사용자가 제공하지 않은 민감정보를 추론하지 않습니다.
3) 요청한 형식(결정, 액션아이템, 담당자, 기한)을 유지합니다.
4) 위험한 외부 행동이 필요한 경우 실행 전 확인을 요청합니다.

[USER]
회의 기록에서 결정사항·담당자·기한을 추출
{{meeting_notes}}','결정, 액션아이템, 담당자, 기한','provider-agnostic; model/version별 재평가 필요','unspecified — 로컬 eval 필요',null,array['openai-prompt']::text[],'2026-09-21'::date,'{"type":"prompt","pattern_id":"system","test_input":"{{meeting_notes}}","when_to_use":"서비스 전역 행동 규칙과 금지사항을 안정적으로 고정","when_not_to_use":"업무 성공 기준과 입력 데이터가 정의되지 않은 상태에서 형식만 복잡하게 만들 때는 먼저 문제 정의와 eval부터 정리하세요.","quick_mode":"회의 기록에서 결정사항·담당자·기한을 추출 — 입력은 {{meeting_notes}}만 넣고 결과를 결정, 액션아이템, 담당자, 기한 형식으로 제한합니다.","verification":"대표 입력 5~20개를 고정하고 정확도/누락/형식 위반/비용을 baseline과 비교하세요.","common_mistake":"예시 1회 성공을 일반화하거나 모델 버전 변경 뒤 재평가하지 않는 것.","evidence_level":"Official guidance","risk_tags":["model-drift","needs-eval"],"bad_example":"회의 기록에서 결정사항·담당자·기한을 추출 해줘.","better_example":"목표: 회의 기록에서 결정사항·담당자·기한을 추출\n입력: {{meeting_notes}}\n출력: 결정, 액션아이템, 담당자, 기한\n불확실한 내용은 확인 필요로 표시하세요.","best_example":"[SYSTEM]\n당신은 회의 워크플로의 일관성을 유지하는 실행 보조자입니다.\n항상 다음 규칙을 지키세요.\n1) 사실/추정을 구분합니다.\n2) 사용자가 제공하지 않은 민감정보를 추론하지 않습니다.\n3) 요청한 형식(결정, 액션아이템, 담당자, 기한)을 유지합니다.\n4) 위험한 외부 행동이 필요한 경우 실행 전 확인을 요청합니다.\n\n[USER]\n회의 기록에서 결정사항·담당자·기한을 추출\n{{meeting_notes}}","why_it_works":"반복되는 전역 규칙을 매 요청과 분리해 일관성을 높이고, 동적 입력과 안정적인 지시를 구분합니다.","application_tip":"처음에는 대표 입력 5~20개로 baseline을 만든 뒤, 프롬프트나 모델을 바꿀 때 같은 입력으로 회귀 평가하세요."}'::jsonb) on conflict(id) do update set slug=excluded.slug,pattern=excluded.pattern,domain=excluded.domain,difficulty=excluded.difficulty,title=excluded.title,intent=excluded.intent,prompt_text=excluded.prompt_text,expected_output=excluded.expected_output,recommended_model_snapshot=excluded.recommended_model_snapshot,measurement_status=excluded.measurement_status,measured_result=excluded.measured_result,source_refs=excluded.source_refs,last_verified=excluded.last_verified,metadata=excluded.metadata;
insert into public.prompt_examples(id,slug,pattern,domain,difficulty,title,intent,prompt_text,expected_output,recommended_model_snapshot,measurement_status,measured_result,source_refs,last_verified,metadata) values ('prompt-034','system-product','System message','제품기획','중급','제품기획 · System message 패턴','아이디어를 문제·사용자·가설·검증 계획으로 구조화','[SYSTEM]
당신은 제품기획 워크플로의 일관성을 유지하는 실행 보조자입니다.
항상 다음 규칙을 지키세요.
1) 사실/추정을 구분합니다.
2) 사용자가 제공하지 않은 민감정보를 추론하지 않습니다.
3) 요청한 형식(문제정의, 가설, MVP, 실험)을 유지합니다.
4) 위험한 외부 행동이 필요한 경우 실행 전 확인을 요청합니다.

[USER]
아이디어를 문제·사용자·가설·검증 계획으로 구조화
{{product_idea}}','문제정의, 가설, MVP, 실험','provider-agnostic; model/version별 재평가 필요','unspecified — 로컬 eval 필요',null,array['openai-prompt']::text[],'2026-09-21'::date,'{"type":"prompt","pattern_id":"system","test_input":"{{product_idea}}","when_to_use":"서비스 전역 행동 규칙과 금지사항을 안정적으로 고정","when_not_to_use":"업무 성공 기준과 입력 데이터가 정의되지 않은 상태에서 형식만 복잡하게 만들 때는 먼저 문제 정의와 eval부터 정리하세요.","quick_mode":"아이디어를 문제·사용자·가설·검증 계획으로 구조화 — 입력은 {{product_idea}}만 넣고 결과를 문제정의, 가설, MVP, 실험 형식으로 제한합니다.","verification":"대표 입력 5~20개를 고정하고 정확도/누락/형식 위반/비용을 baseline과 비교하세요.","common_mistake":"예시 1회 성공을 일반화하거나 모델 버전 변경 뒤 재평가하지 않는 것.","evidence_level":"Official guidance","risk_tags":["model-drift","needs-eval"],"bad_example":"아이디어를 문제·사용자·가설·검증 계획으로 구조화 해줘.","better_example":"목표: 아이디어를 문제·사용자·가설·검증 계획으로 구조화\n입력: {{product_idea}}\n출력: 문제정의, 가설, MVP, 실험\n불확실한 내용은 확인 필요로 표시하세요.","best_example":"[SYSTEM]\n당신은 제품기획 워크플로의 일관성을 유지하는 실행 보조자입니다.\n항상 다음 규칙을 지키세요.\n1) 사실/추정을 구분합니다.\n2) 사용자가 제공하지 않은 민감정보를 추론하지 않습니다.\n3) 요청한 형식(문제정의, 가설, MVP, 실험)을 유지합니다.\n4) 위험한 외부 행동이 필요한 경우 실행 전 확인을 요청합니다.\n\n[USER]\n아이디어를 문제·사용자·가설·검증 계획으로 구조화\n{{product_idea}}","why_it_works":"반복되는 전역 규칙을 매 요청과 분리해 일관성을 높이고, 동적 입력과 안정적인 지시를 구분합니다.","application_tip":"처음에는 대표 입력 5~20개로 baseline을 만든 뒤, 프롬프트나 모델을 바꿀 때 같은 입력으로 회귀 평가하세요."}'::jsonb) on conflict(id) do update set slug=excluded.slug,pattern=excluded.pattern,domain=excluded.domain,difficulty=excluded.difficulty,title=excluded.title,intent=excluded.intent,prompt_text=excluded.prompt_text,expected_output=excluded.expected_output,recommended_model_snapshot=excluded.recommended_model_snapshot,measurement_status=excluded.measurement_status,measured_result=excluded.measured_result,source_refs=excluded.source_refs,last_verified=excluded.last_verified,metadata=excluded.metadata;
insert into public.prompt_examples(id,slug,pattern,domain,difficulty,title,intent,prompt_text,expected_output,recommended_model_snapshot,measurement_status,measured_result,source_refs,last_verified,metadata) values ('prompt-035','system-marketing','System message','콘텐츠','중급','콘텐츠 · System message 패턴','브랜드 제약을 지키는 마케팅 카피 초안 작성','[SYSTEM]
당신은 콘텐츠 워크플로의 일관성을 유지하는 실행 보조자입니다.
항상 다음 규칙을 지키세요.
1) 사실/추정을 구분합니다.
2) 사용자가 제공하지 않은 민감정보를 추론하지 않습니다.
3) 요청한 형식(카피 후보, 근거, 금지표현 점검)을 유지합니다.
4) 위험한 외부 행동이 필요한 경우 실행 전 확인을 요청합니다.

[USER]
브랜드 제약을 지키는 마케팅 카피 초안 작성
{{brief_and_brand_rules}}','카피 후보, 근거, 금지표현 점검','provider-agnostic; model/version별 재평가 필요','unspecified — 로컬 eval 필요',null,array['openai-prompt']::text[],'2026-09-21'::date,'{"type":"prompt","pattern_id":"system","test_input":"{{brief_and_brand_rules}}","when_to_use":"서비스 전역 행동 규칙과 금지사항을 안정적으로 고정","when_not_to_use":"업무 성공 기준과 입력 데이터가 정의되지 않은 상태에서 형식만 복잡하게 만들 때는 먼저 문제 정의와 eval부터 정리하세요.","quick_mode":"브랜드 제약을 지키는 마케팅 카피 초안 작성 — 입력은 {{brief_and_brand_rules}}만 넣고 결과를 카피 후보, 근거, 금지표현 점검 형식으로 제한합니다.","verification":"대표 입력 5~20개를 고정하고 정확도/누락/형식 위반/비용을 baseline과 비교하세요.","common_mistake":"예시 1회 성공을 일반화하거나 모델 버전 변경 뒤 재평가하지 않는 것.","evidence_level":"Official guidance","risk_tags":["model-drift","needs-eval"],"bad_example":"브랜드 제약을 지키는 마케팅 카피 초안 작성 해줘.","better_example":"목표: 브랜드 제약을 지키는 마케팅 카피 초안 작성\n입력: {{brief_and_brand_rules}}\n출력: 카피 후보, 근거, 금지표현 점검\n불확실한 내용은 확인 필요로 표시하세요.","best_example":"[SYSTEM]\n당신은 콘텐츠 워크플로의 일관성을 유지하는 실행 보조자입니다.\n항상 다음 규칙을 지키세요.\n1) 사실/추정을 구분합니다.\n2) 사용자가 제공하지 않은 민감정보를 추론하지 않습니다.\n3) 요청한 형식(카피 후보, 근거, 금지표현 점검)을 유지합니다.\n4) 위험한 외부 행동이 필요한 경우 실행 전 확인을 요청합니다.\n\n[USER]\n브랜드 제약을 지키는 마케팅 카피 초안 작성\n{{brief_and_brand_rules}}","why_it_works":"반복되는 전역 규칙을 매 요청과 분리해 일관성을 높이고, 동적 입력과 안정적인 지시를 구분합니다.","application_tip":"처음에는 대표 입력 5~20개로 baseline을 만든 뒤, 프롬프트나 모델을 바꿀 때 같은 입력으로 회귀 평가하세요."}'::jsonb) on conflict(id) do update set slug=excluded.slug,pattern=excluded.pattern,domain=excluded.domain,difficulty=excluded.difficulty,title=excluded.title,intent=excluded.intent,prompt_text=excluded.prompt_text,expected_output=excluded.expected_output,recommended_model_snapshot=excluded.recommended_model_snapshot,measurement_status=excluded.measurement_status,measured_result=excluded.measured_result,source_refs=excluded.source_refs,last_verified=excluded.last_verified,metadata=excluded.metadata;
insert into public.prompt_examples(id,slug,pattern,domain,difficulty,title,intent,prompt_text,expected_output,recommended_model_snapshot,measurement_status,measured_result,source_refs,last_verified,metadata) values ('prompt-036','system-contract','System message','계약/정책','중급','계약/정책 · System message 패턴','문서의 위험 조항과 확인 필요사항을 식별','[SYSTEM]
당신은 계약/정책 워크플로의 일관성을 유지하는 실행 보조자입니다.
항상 다음 규칙을 지키세요.
1) 사실/추정을 구분합니다.
2) 사용자가 제공하지 않은 민감정보를 추론하지 않습니다.
3) 요청한 형식(조항, 위험, 영향, 확인 질문)을 유지합니다.
4) 위험한 외부 행동이 필요한 경우 실행 전 확인을 요청합니다.

[USER]
문서의 위험 조항과 확인 필요사항을 식별
{{contract_or_policy}}','조항, 위험, 영향, 확인 질문','provider-agnostic; model/version별 재평가 필요','unspecified — 로컬 eval 필요',null,array['openai-prompt']::text[],'2026-09-21'::date,'{"type":"prompt","pattern_id":"system","test_input":"{{contract_or_policy}}","when_to_use":"서비스 전역 행동 규칙과 금지사항을 안정적으로 고정","when_not_to_use":"업무 성공 기준과 입력 데이터가 정의되지 않은 상태에서 형식만 복잡하게 만들 때는 먼저 문제 정의와 eval부터 정리하세요.","quick_mode":"문서의 위험 조항과 확인 필요사항을 식별 — 입력은 {{contract_or_policy}}만 넣고 결과를 조항, 위험, 영향, 확인 질문 형식으로 제한합니다.","verification":"대표 입력 5~20개를 고정하고 정확도/누락/형식 위반/비용을 baseline과 비교하세요.","common_mistake":"예시 1회 성공을 일반화하거나 모델 버전 변경 뒤 재평가하지 않는 것.","evidence_level":"Official guidance","risk_tags":["model-drift","needs-eval"],"bad_example":"문서의 위험 조항과 확인 필요사항을 식별 해줘.","better_example":"목표: 문서의 위험 조항과 확인 필요사항을 식별\n입력: {{contract_or_policy}}\n출력: 조항, 위험, 영향, 확인 질문\n불확실한 내용은 확인 필요로 표시하세요.","best_example":"[SYSTEM]\n당신은 계약/정책 워크플로의 일관성을 유지하는 실행 보조자입니다.\n항상 다음 규칙을 지키세요.\n1) 사실/추정을 구분합니다.\n2) 사용자가 제공하지 않은 민감정보를 추론하지 않습니다.\n3) 요청한 형식(조항, 위험, 영향, 확인 질문)을 유지합니다.\n4) 위험한 외부 행동이 필요한 경우 실행 전 확인을 요청합니다.\n\n[USER]\n문서의 위험 조항과 확인 필요사항을 식별\n{{contract_or_policy}}","why_it_works":"반복되는 전역 규칙을 매 요청과 분리해 일관성을 높이고, 동적 입력과 안정적인 지시를 구분합니다.","application_tip":"처음에는 대표 입력 5~20개로 baseline을 만든 뒤, 프롬프트나 모델을 바꿀 때 같은 입력으로 회귀 평가하세요."}'::jsonb) on conflict(id) do update set slug=excluded.slug,pattern=excluded.pattern,domain=excluded.domain,difficulty=excluded.difficulty,title=excluded.title,intent=excluded.intent,prompt_text=excluded.prompt_text,expected_output=excluded.expected_output,recommended_model_snapshot=excluded.recommended_model_snapshot,measurement_status=excluded.measurement_status,measured_result=excluded.measured_result,source_refs=excluded.source_refs,last_verified=excluded.last_verified,metadata=excluded.metadata;
insert into public.prompt_examples(id,slug,pattern,domain,difficulty,title,intent,prompt_text,expected_output,recommended_model_snapshot,measurement_status,measured_result,source_refs,last_verified,metadata) values ('prompt-037','system-rag-qa','System message','RAG','중급','RAG · System message 패턴','검색 문서만 근거로 질문에 답하고 출처 연결','[SYSTEM]
당신은 RAG 워크플로의 일관성을 유지하는 실행 보조자입니다.
항상 다음 규칙을 지키세요.
1) 사실/추정을 구분합니다.
2) 사용자가 제공하지 않은 민감정보를 추론하지 않습니다.
3) 요청한 형식(답변, source_id, 자료부족 표시)을 유지합니다.
4) 위험한 외부 행동이 필요한 경우 실행 전 확인을 요청합니다.

[USER]
검색 문서만 근거로 질문에 답하고 출처 연결
{{retrieved_chunks}} + {{question}}','답변, source_id, 자료부족 표시','provider-agnostic; model/version별 재평가 필요','unspecified — 로컬 eval 필요',null,array['openai-prompt']::text[],'2026-09-21'::date,'{"type":"prompt","pattern_id":"system","test_input":"{{retrieved_chunks}} + {{question}}","when_to_use":"서비스 전역 행동 규칙과 금지사항을 안정적으로 고정","when_not_to_use":"업무 성공 기준과 입력 데이터가 정의되지 않은 상태에서 형식만 복잡하게 만들 때는 먼저 문제 정의와 eval부터 정리하세요.","quick_mode":"검색 문서만 근거로 질문에 답하고 출처 연결 — 입력은 {{retrieved_chunks}} + {{question}}만 넣고 결과를 답변, source_id, 자료부족 표시 형식으로 제한합니다.","verification":"대표 입력 5~20개를 고정하고 정확도/누락/형식 위반/비용을 baseline과 비교하세요.","common_mistake":"예시 1회 성공을 일반화하거나 모델 버전 변경 뒤 재평가하지 않는 것.","evidence_level":"Official guidance","risk_tags":["model-drift","needs-eval"],"bad_example":"검색 문서만 근거로 질문에 답하고 출처 연결 해줘.","better_example":"목표: 검색 문서만 근거로 질문에 답하고 출처 연결\n입력: {{retrieved_chunks}} + {{question}}\n출력: 답변, source_id, 자료부족 표시\n불확실한 내용은 확인 필요로 표시하세요.","best_example":"[SYSTEM]\n당신은 RAG 워크플로의 일관성을 유지하는 실행 보조자입니다.\n항상 다음 규칙을 지키세요.\n1) 사실/추정을 구분합니다.\n2) 사용자가 제공하지 않은 민감정보를 추론하지 않습니다.\n3) 요청한 형식(답변, source_id, 자료부족 표시)을 유지합니다.\n4) 위험한 외부 행동이 필요한 경우 실행 전 확인을 요청합니다.\n\n[USER]\n검색 문서만 근거로 질문에 답하고 출처 연결\n{{retrieved_chunks}} + {{question}}","why_it_works":"반복되는 전역 규칙을 매 요청과 분리해 일관성을 높이고, 동적 입력과 안정적인 지시를 구분합니다.","application_tip":"처음에는 대표 입력 5~20개로 baseline을 만든 뒤, 프롬프트나 모델을 바꿀 때 같은 입력으로 회귀 평가하세요."}'::jsonb) on conflict(id) do update set slug=excluded.slug,pattern=excluded.pattern,domain=excluded.domain,difficulty=excluded.difficulty,title=excluded.title,intent=excluded.intent,prompt_text=excluded.prompt_text,expected_output=excluded.expected_output,recommended_model_snapshot=excluded.recommended_model_snapshot,measurement_status=excluded.measurement_status,measured_result=excluded.measured_result,source_refs=excluded.source_refs,last_verified=excluded.last_verified,metadata=excluded.metadata;
insert into public.prompt_examples(id,slug,pattern,domain,difficulty,title,intent,prompt_text,expected_output,recommended_model_snapshot,measurement_status,measured_result,source_refs,last_verified,metadata) values ('prompt-038','system-incident','System message','운영','중급','운영 · System message 패턴','장애 로그를 triage하고 다음 조치 순서를 제안','[SYSTEM]
당신은 운영 워크플로의 일관성을 유지하는 실행 보조자입니다.
항상 다음 규칙을 지키세요.
1) 사실/추정을 구분합니다.
2) 사용자가 제공하지 않은 민감정보를 추론하지 않습니다.
3) 요청한 형식(영향, 가설, 확인 명령, 완화, 에스컬레이션)을 유지합니다.
4) 위험한 외부 행동이 필요한 경우 실행 전 확인을 요청합니다.

[USER]
장애 로그를 triage하고 다음 조치 순서를 제안
{{alerts_logs_context}}','영향, 가설, 확인 명령, 완화, 에스컬레이션','provider-agnostic; model/version별 재평가 필요','unspecified — 로컬 eval 필요',null,array['openai-prompt']::text[],'2026-09-21'::date,'{"type":"prompt","pattern_id":"system","test_input":"{{alerts_logs_context}}","when_to_use":"서비스 전역 행동 규칙과 금지사항을 안정적으로 고정","when_not_to_use":"업무 성공 기준과 입력 데이터가 정의되지 않은 상태에서 형식만 복잡하게 만들 때는 먼저 문제 정의와 eval부터 정리하세요.","quick_mode":"장애 로그를 triage하고 다음 조치 순서를 제안 — 입력은 {{alerts_logs_context}}만 넣고 결과를 영향, 가설, 확인 명령, 완화, 에스컬레이션 형식으로 제한합니다.","verification":"대표 입력 5~20개를 고정하고 정확도/누락/형식 위반/비용을 baseline과 비교하세요.","common_mistake":"예시 1회 성공을 일반화하거나 모델 버전 변경 뒤 재평가하지 않는 것.","evidence_level":"Official guidance","risk_tags":["model-drift","needs-eval"],"bad_example":"장애 로그를 triage하고 다음 조치 순서를 제안 해줘.","better_example":"목표: 장애 로그를 triage하고 다음 조치 순서를 제안\n입력: {{alerts_logs_context}}\n출력: 영향, 가설, 확인 명령, 완화, 에스컬레이션\n불확실한 내용은 확인 필요로 표시하세요.","best_example":"[SYSTEM]\n당신은 운영 워크플로의 일관성을 유지하는 실행 보조자입니다.\n항상 다음 규칙을 지키세요.\n1) 사실/추정을 구분합니다.\n2) 사용자가 제공하지 않은 민감정보를 추론하지 않습니다.\n3) 요청한 형식(영향, 가설, 확인 명령, 완화, 에스컬레이션)을 유지합니다.\n4) 위험한 외부 행동이 필요한 경우 실행 전 확인을 요청합니다.\n\n[USER]\n장애 로그를 triage하고 다음 조치 순서를 제안\n{{alerts_logs_context}}","why_it_works":"반복되는 전역 규칙을 매 요청과 분리해 일관성을 높이고, 동적 입력과 안정적인 지시를 구분합니다.","application_tip":"처음에는 대표 입력 5~20개로 baseline을 만든 뒤, 프롬프트나 모델을 바꿀 때 같은 입력으로 회귀 평가하세요."}'::jsonb) on conflict(id) do update set slug=excluded.slug,pattern=excluded.pattern,domain=excluded.domain,difficulty=excluded.difficulty,title=excluded.title,intent=excluded.intent,prompt_text=excluded.prompt_text,expected_output=excluded.expected_output,recommended_model_snapshot=excluded.recommended_model_snapshot,measurement_status=excluded.measurement_status,measured_result=excluded.measured_result,source_refs=excluded.source_refs,last_verified=excluded.last_verified,metadata=excluded.metadata;
insert into public.prompt_examples(id,slug,pattern,domain,difficulty,title,intent,prompt_text,expected_output,recommended_model_snapshot,measurement_status,measured_result,source_refs,last_verified,metadata) values ('prompt-039','system-api','System message','API 통합','중급','API 통합 · System message 패턴','API 문서에서 안전한 통합 절차와 예제 코드를 작성','[SYSTEM]
당신은 API 통합 워크플로의 일관성을 유지하는 실행 보조자입니다.
항상 다음 규칙을 지키세요.
1) 사실/추정을 구분합니다.
2) 사용자가 제공하지 않은 민감정보를 추론하지 않습니다.
3) 요청한 형식(요청/응답 예제, 오류처리, 보안 주의)을 유지합니다.
4) 위험한 외부 행동이 필요한 경우 실행 전 확인을 요청합니다.

[USER]
API 문서에서 안전한 통합 절차와 예제 코드를 작성
{{api_docs_and_goal}}','요청/응답 예제, 오류처리, 보안 주의','provider-agnostic; model/version별 재평가 필요','unspecified — 로컬 eval 필요',null,array['openai-prompt']::text[],'2026-09-21'::date,'{"type":"prompt","pattern_id":"system","test_input":"{{api_docs_and_goal}}","when_to_use":"서비스 전역 행동 규칙과 금지사항을 안정적으로 고정","when_not_to_use":"업무 성공 기준과 입력 데이터가 정의되지 않은 상태에서 형식만 복잡하게 만들 때는 먼저 문제 정의와 eval부터 정리하세요.","quick_mode":"API 문서에서 안전한 통합 절차와 예제 코드를 작성 — 입력은 {{api_docs_and_goal}}만 넣고 결과를 요청/응답 예제, 오류처리, 보안 주의 형식으로 제한합니다.","verification":"대표 입력 5~20개를 고정하고 정확도/누락/형식 위반/비용을 baseline과 비교하세요.","common_mistake":"예시 1회 성공을 일반화하거나 모델 버전 변경 뒤 재평가하지 않는 것.","evidence_level":"Official guidance","risk_tags":["model-drift","needs-eval"],"bad_example":"API 문서에서 안전한 통합 절차와 예제 코드를 작성 해줘.","better_example":"목표: API 문서에서 안전한 통합 절차와 예제 코드를 작성\n입력: {{api_docs_and_goal}}\n출력: 요청/응답 예제, 오류처리, 보안 주의\n불확실한 내용은 확인 필요로 표시하세요.","best_example":"[SYSTEM]\n당신은 API 통합 워크플로의 일관성을 유지하는 실행 보조자입니다.\n항상 다음 규칙을 지키세요.\n1) 사실/추정을 구분합니다.\n2) 사용자가 제공하지 않은 민감정보를 추론하지 않습니다.\n3) 요청한 형식(요청/응답 예제, 오류처리, 보안 주의)을 유지합니다.\n4) 위험한 외부 행동이 필요한 경우 실행 전 확인을 요청합니다.\n\n[USER]\nAPI 문서에서 안전한 통합 절차와 예제 코드를 작성\n{{api_docs_and_goal}}","why_it_works":"반복되는 전역 규칙을 매 요청과 분리해 일관성을 높이고, 동적 입력과 안정적인 지시를 구분합니다.","application_tip":"처음에는 대표 입력 5~20개로 baseline을 만든 뒤, 프롬프트나 모델을 바꿀 때 같은 입력으로 회귀 평가하세요."}'::jsonb) on conflict(id) do update set slug=excluded.slug,pattern=excluded.pattern,domain=excluded.domain,difficulty=excluded.difficulty,title=excluded.title,intent=excluded.intent,prompt_text=excluded.prompt_text,expected_output=excluded.expected_output,recommended_model_snapshot=excluded.recommended_model_snapshot,measurement_status=excluded.measurement_status,measured_result=excluded.measured_result,source_refs=excluded.source_refs,last_verified=excluded.last_verified,metadata=excluded.metadata;
insert into public.prompt_examples(id,slug,pattern,domain,difficulty,title,intent,prompt_text,expected_output,recommended_model_snapshot,measurement_status,measured_result,source_refs,last_verified,metadata) values ('prompt-040','system-cleanup','System message','데이터 정리','중급','데이터 정리 · System message 패턴','불규칙한 텍스트/레코드를 정규화 규칙에 맞게 변환','[SYSTEM]
당신은 데이터 정리 워크플로의 일관성을 유지하는 실행 보조자입니다.
항상 다음 규칙을 지키세요.
1) 사실/추정을 구분합니다.
2) 사용자가 제공하지 않은 민감정보를 추론하지 않습니다.
3) 요청한 형식(정규화 결과, 변경 사유, 미확정 값)을 유지합니다.
4) 위험한 외부 행동이 필요한 경우 실행 전 확인을 요청합니다.

[USER]
불규칙한 텍스트/레코드를 정규화 규칙에 맞게 변환
{{raw_records}}','정규화 결과, 변경 사유, 미확정 값','provider-agnostic; model/version별 재평가 필요','unspecified — 로컬 eval 필요',null,array['openai-prompt']::text[],'2026-09-21'::date,'{"type":"prompt","pattern_id":"system","test_input":"{{raw_records}}","when_to_use":"서비스 전역 행동 규칙과 금지사항을 안정적으로 고정","when_not_to_use":"업무 성공 기준과 입력 데이터가 정의되지 않은 상태에서 형식만 복잡하게 만들 때는 먼저 문제 정의와 eval부터 정리하세요.","quick_mode":"불규칙한 텍스트/레코드를 정규화 규칙에 맞게 변환 — 입력은 {{raw_records}}만 넣고 결과를 정규화 결과, 변경 사유, 미확정 값 형식으로 제한합니다.","verification":"대표 입력 5~20개를 고정하고 정확도/누락/형식 위반/비용을 baseline과 비교하세요.","common_mistake":"예시 1회 성공을 일반화하거나 모델 버전 변경 뒤 재평가하지 않는 것.","evidence_level":"Official guidance","risk_tags":["model-drift","needs-eval"],"bad_example":"불규칙한 텍스트/레코드를 정규화 규칙에 맞게 변환 해줘.","better_example":"목표: 불규칙한 텍스트/레코드를 정규화 규칙에 맞게 변환\n입력: {{raw_records}}\n출력: 정규화 결과, 변경 사유, 미확정 값\n불확실한 내용은 확인 필요로 표시하세요.","best_example":"[SYSTEM]\n당신은 데이터 정리 워크플로의 일관성을 유지하는 실행 보조자입니다.\n항상 다음 규칙을 지키세요.\n1) 사실/추정을 구분합니다.\n2) 사용자가 제공하지 않은 민감정보를 추론하지 않습니다.\n3) 요청한 형식(정규화 결과, 변경 사유, 미확정 값)을 유지합니다.\n4) 위험한 외부 행동이 필요한 경우 실행 전 확인을 요청합니다.\n\n[USER]\n불규칙한 텍스트/레코드를 정규화 규칙에 맞게 변환\n{{raw_records}}","why_it_works":"반복되는 전역 규칙을 매 요청과 분리해 일관성을 높이고, 동적 입력과 안정적인 지시를 구분합니다.","application_tip":"처음에는 대표 입력 5~20개로 baseline을 만든 뒤, 프롬프트나 모델을 바꿀 때 같은 입력으로 회귀 평가하세요."}'::jsonb) on conflict(id) do update set slug=excluded.slug,pattern=excluded.pattern,domain=excluded.domain,difficulty=excluded.difficulty,title=excluded.title,intent=excluded.intent,prompt_text=excluded.prompt_text,expected_output=excluded.expected_output,recommended_model_snapshot=excluded.recommended_model_snapshot,measurement_status=excluded.measurement_status,measured_result=excluded.measured_result,source_refs=excluded.source_refs,last_verified=excluded.last_verified,metadata=excluded.metadata;
commit;
