-- LLM Bible v2.1.1 category seed: 70-failure-prompt-context.sql
-- Safe to re-run: ON CONFLICT DO UPDATE.
begin;
insert into public.failure_patterns(id,title,symptom,root_cause,corrected_example,prevention,test_eval,source_refs,last_verified,metadata) values ('failure-01','Model drift','모델 업데이트 뒤 같은 프롬프트 결과가 달라짐','모델/스냅샷 고정 없이 프롬프트만 관리','model + version + regression eval','model + version + regression eval','실패 재현용 작은 eval case를 만들고 변경 전/후의 실패율을 비교하세요.',array['anthropic-eval']::text[],'2026-09-21'::date,'{"type":"anti_pattern","bad_example":"모델/스냅샷 고정 없이 프롬프트만 관리 상태로 결과만 보고 운영합니다.","evidence_level":"Research/official pattern"}'::jsonb) on conflict(id) do update set title=excluded.title,symptom=excluded.symptom,root_cause=excluded.root_cause,corrected_example=excluded.corrected_example,prevention=excluded.prevention,test_eval=excluded.test_eval,source_refs=excluded.source_refs,last_verified=excluded.last_verified,metadata=excluded.metadata;
insert into public.failure_patterns(id,title,symptom,root_cause,corrected_example,prevention,test_eval,source_refs,last_verified,metadata) values ('failure-03','Too much context','긴 문맥을 많이 넣을수록 오히려 답이 흔들림','관련성 필터 없이 top-k/전체문서 주입','retrieval/top-k/position eval','retrieval/top-k/position eval','실패 재현용 작은 eval case를 만들고 변경 전/후의 실패율을 비교하세요.',array['anthropic-eval']::text[],'2026-09-21'::date,'{"type":"anti_pattern","bad_example":"관련성 필터 없이 top-k/전체문서 주입 상태로 결과만 보고 운영합니다.","evidence_level":"Research/official pattern"}'::jsonb) on conflict(id) do update set title=excluded.title,symptom=excluded.symptom,root_cause=excluded.root_cause,corrected_example=excluded.corrected_example,prevention=excluded.prevention,test_eval=excluded.test_eval,source_refs=excluded.source_refs,last_verified=excluded.last_verified,metadata=excluded.metadata;
insert into public.failure_patterns(id,title,symptom,root_cause,corrected_example,prevention,test_eval,source_refs,last_verified,metadata) values ('failure-12','Stale source','최신 정보 질문에 오래된 지식으로 답함','검색/RAG/last_verified 없음','freshness tier + live source','freshness tier + live source','실패 재현용 작은 eval case를 만들고 변경 전/후의 실패율을 비교하세요.',array['anthropic-eval']::text[],'2026-09-21'::date,'{"type":"anti_pattern","bad_example":"검색/RAG/last_verified 없음 상태로 결과만 보고 운영합니다.","evidence_level":"Research/official pattern"}'::jsonb) on conflict(id) do update set title=excluded.title,symptom=excluded.symptom,root_cause=excluded.root_cause,corrected_example=excluded.corrected_example,prevention=excluded.prevention,test_eval=excluded.test_eval,source_refs=excluded.source_refs,last_verified=excluded.last_verified,metadata=excluded.metadata;
insert into public.failure_patterns(id,title,symptom,root_cause,corrected_example,prevention,test_eval,source_refs,last_verified,metadata) values ('failure-14','Over-roleplay','불필요한 역할극이 길고 제약과 충돌','역할을 품질 향상의 만능열쇠로 사용','역할보다 목표/입력/출력/검증을 우선','역할보다 목표/입력/출력/검증을 우선','실패 재현용 작은 eval case를 만들고 변경 전/후의 실패율을 비교하세요.',array['owasp']::text[],'2026-09-21'::date,'{"type":"anti_pattern","bad_example":"역할을 품질 향상의 만능열쇠로 사용 상태로 결과만 보고 운영합니다.","evidence_level":"Research/official pattern"}'::jsonb) on conflict(id) do update set title=excluded.title,symptom=excluded.symptom,root_cause=excluded.root_cause,corrected_example=excluded.corrected_example,prevention=excluded.prevention,test_eval=excluded.test_eval,source_refs=excluded.source_refs,last_verified=excluded.last_verified,metadata=excluded.metadata;
insert into public.failure_patterns(id,title,symptom,root_cause,corrected_example,prevention,test_eval,source_refs,last_verified,metadata) values ('failure-15','Conflicting instructions','모델이 지시 일부를 무시','우선순위가 다른 규칙이 한 블록에 섞임','system/user/data 경계와 우선순위 정리','system/user/data 경계와 우선순위 정리','실패 재현용 작은 eval case를 만들고 변경 전/후의 실패율을 비교하세요.',array['anthropic-eval']::text[],'2026-09-21'::date,'{"type":"anti_pattern","bad_example":"우선순위가 다른 규칙이 한 블록에 섞임 상태로 결과만 보고 운영합니다.","evidence_level":"Research/official pattern"}'::jsonb) on conflict(id) do update set title=excluded.title,symptom=excluded.symptom,root_cause=excluded.root_cause,corrected_example=excluded.corrected_example,prevention=excluded.prevention,test_eval=excluded.test_eval,source_refs=excluded.source_refs,last_verified=excluded.last_verified,metadata=excluded.metadata;
insert into public.failure_patterns(id,title,symptom,root_cause,corrected_example,prevention,test_eval,source_refs,last_verified,metadata) values ('failure-16','Unbounded CoT request','불필요하게 긴 사고과정을 요구','내부 추론 노출을 품질과 동일시','Plan→Evidence/Tool→Result→Verification','Plan→Evidence/Tool→Result→Verification','실패 재현용 작은 eval case를 만들고 변경 전/후의 실패율을 비교하세요.',array['anthropic-eval']::text[],'2026-09-21'::date,'{"type":"anti_pattern","bad_example":"내부 추론 노출을 품질과 동일시 상태로 결과만 보고 운영합니다.","evidence_level":"Research/official pattern"}'::jsonb) on conflict(id) do update set title=excluded.title,symptom=excluded.symptom,root_cause=excluded.root_cause,corrected_example=excluded.corrected_example,prevention=excluded.prevention,test_eval=excluded.test_eval,source_refs=excluded.source_refs,last_verified=excluded.last_verified,metadata=excluded.metadata;
commit;
