-- LLM Bible v2.1.1 category seed: 70-failure-tools-agents.sql
-- Safe to re-run: ON CONFLICT DO UPDATE.
begin;
insert into public.failure_patterns(id,title,symptom,root_cause,corrected_example,prevention,test_eval,source_refs,last_verified,metadata) values ('failure-05','Weak tool schema','잘못된 인자/모호한 tool 선택','도구 설명·enum·필수 필드가 약함','좁은 JSON Schema + 서버 검증','좁은 JSON Schema + 서버 검증','실패 재현용 작은 eval case를 만들고 변경 전/후의 실패율을 비교하세요.',array['anthropic-eval']::text[],'2026-09-21'::date,'{"type":"anti_pattern","bad_example":"도구 설명·enum·필수 필드가 약함 상태로 결과만 보고 운영합니다.","evidence_level":"Research/official pattern"}'::jsonb) on conflict(id) do update set title=excluded.title,symptom=excluded.symptom,root_cause=excluded.root_cause,corrected_example=excluded.corrected_example,prevention=excluded.prevention,test_eval=excluded.test_eval,source_refs=excluded.source_refs,last_verified=excluded.last_verified,metadata=excluded.metadata;
insert into public.failure_patterns(id,title,symptom,root_cause,corrected_example,prevention,test_eval,source_refs,last_verified,metadata) values ('failure-06','Tool loop','같은 오류를 계속 재시도','retry/step budget과 error classification 없음','bounded retry + stop condition','bounded retry + stop condition','실패 재현용 작은 eval case를 만들고 변경 전/후의 실패율을 비교하세요.',array['anthropic-eval']::text[],'2026-09-21'::date,'{"type":"anti_pattern","bad_example":"retry/step budget과 error classification 없음 상태로 결과만 보고 운영합니다.","evidence_level":"Research/official pattern"}'::jsonb) on conflict(id) do update set title=excluded.title,symptom=excluded.symptom,root_cause=excluded.root_cause,corrected_example=excluded.corrected_example,prevention=excluded.prevention,test_eval=excluded.test_eval,source_refs=excluded.source_refs,last_verified=excluded.last_verified,metadata=excluded.metadata;
insert into public.failure_patterns(id,title,symptom,root_cause,corrected_example,prevention,test_eval,source_refs,last_verified,metadata) values ('failure-24','Retry without idempotency','재시도 때 결제/생성이 중복','쓰기 작업 idempotency 없음','idempotency key + 상태 확인','idempotency key + 상태 확인','실패 재현용 작은 eval case를 만들고 변경 전/후의 실패율을 비교하세요.',array['anthropic-eval']::text[],'2026-09-21'::date,'{"type":"anti_pattern","bad_example":"쓰기 작업 idempotency 없음 상태로 결과만 보고 운영합니다.","evidence_level":"Research/official pattern"}'::jsonb) on conflict(id) do update set title=excluded.title,symptom=excluded.symptom,root_cause=excluded.root_cause,corrected_example=excluded.corrected_example,prevention=excluded.prevention,test_eval=excluded.test_eval,source_refs=excluded.source_refs,last_verified=excluded.last_verified,metadata=excluded.metadata;
insert into public.failure_patterns(id,title,symptom,root_cause,corrected_example,prevention,test_eval,source_refs,last_verified,metadata) values ('failure-25','Agent where workflow is enough','단순 순차 업무에 자유형 agent 사용','제어 가능한 workflow를 과도하게 agent화','deterministic workflow 우선','deterministic workflow 우선','실패 재현용 작은 eval case를 만들고 변경 전/후의 실패율을 비교하세요.',array['anthropic-eval']::text[],'2026-09-21'::date,'{"type":"anti_pattern","bad_example":"제어 가능한 workflow를 과도하게 agent화 상태로 결과만 보고 운영합니다.","evidence_level":"Research/official pattern"}'::jsonb) on conflict(id) do update set title=excluded.title,symptom=excluded.symptom,root_cause=excluded.root_cause,corrected_example=excluded.corrected_example,prevention=excluded.prevention,test_eval=excluded.test_eval,source_refs=excluded.source_refs,last_verified=excluded.last_verified,metadata=excluded.metadata;
insert into public.failure_patterns(id,title,symptom,root_cause,corrected_example,prevention,test_eval,source_refs,last_verified,metadata) values ('failure-26','Multi-agent overuse','비용/지연은 늘고 품질은 그대로','역할 분할이 실제 병렬성/전문성 없이 형식적','single-agent baseline과 cost/success 비교','single-agent baseline과 cost/success 비교','실패 재현용 작은 eval case를 만들고 변경 전/후의 실패율을 비교하세요.',array['anthropic-eval']::text[],'2026-09-21'::date,'{"type":"anti_pattern","bad_example":"역할 분할이 실제 병렬성/전문성 없이 형식적 상태로 결과만 보고 운영합니다.","evidence_level":"Research/official pattern"}'::jsonb) on conflict(id) do update set title=excluded.title,symptom=excluded.symptom,root_cause=excluded.root_cause,corrected_example=excluded.corrected_example,prevention=excluded.prevention,test_eval=excluded.test_eval,source_refs=excluded.source_refs,last_verified=excluded.last_verified,metadata=excluded.metadata;
insert into public.failure_patterns(id,title,symptom,root_cause,corrected_example,prevention,test_eval,source_refs,last_verified,metadata) values ('failure-27','Missing tool-result compression','도구 결과가 그대로 context를 잠식','필요 필드 필터링 없음','tool schema 기반 요약/압축','tool schema 기반 요약/압축','실패 재현용 작은 eval case를 만들고 변경 전/후의 실패율을 비교하세요.',array['anthropic-eval']::text[],'2026-09-21'::date,'{"type":"anti_pattern","bad_example":"필요 필드 필터링 없음 상태로 결과만 보고 운영합니다.","evidence_level":"Research/official pattern"}'::jsonb) on conflict(id) do update set title=excluded.title,symptom=excluded.symptom,root_cause=excluded.root_cause,corrected_example=excluded.corrected_example,prevention=excluded.prevention,test_eval=excluded.test_eval,source_refs=excluded.source_refs,last_verified=excluded.last_verified,metadata=excluded.metadata;
commit;
