-- LLM Bible v2.1.1 category seed: 70-failure-rag-grounding.sql
-- Safe to re-run: ON CONFLICT DO UPDATE.
begin;
insert into public.failure_patterns(id,title,symptom,root_cause,corrected_example,prevention,test_eval,source_refs,last_verified,metadata) values ('failure-04','RAG hallucination','검색 결과에 없는 내용을 사실처럼 답함','grounding 규칙과 faithfulness 평가 없음','citation + abstention + faithfulness','citation + abstention + faithfulness','실패 재현용 작은 eval case를 만들고 변경 전/후의 실패율을 비교하세요.',array['anthropic-eval']::text[],'2026-09-21'::date,'{"type":"anti_pattern","bad_example":"grounding 규칙과 faithfulness 평가 없음 상태로 결과만 보고 운영합니다.","evidence_level":"Research/official pattern"}'::jsonb) on conflict(id) do update set title=excluded.title,symptom=excluded.symptom,root_cause=excluded.root_cause,corrected_example=excluded.corrected_example,prevention=excluded.prevention,test_eval=excluded.test_eval,source_refs=excluded.source_refs,last_verified=excluded.last_verified,metadata=excluded.metadata;
insert into public.failure_patterns(id,title,symptom,root_cause,corrected_example,prevention,test_eval,source_refs,last_verified,metadata) values ('failure-17','Retrieval noise','RAG 답변이 관련 없는 문서에 끌림','top-k 과다/리랭킹 없음','retrieval recall과 precision을 같이 평가','retrieval recall과 precision을 같이 평가','실패 재현용 작은 eval case를 만들고 변경 전/후의 실패율을 비교하세요.',array['anthropic-eval']::text[],'2026-09-21'::date,'{"type":"anti_pattern","bad_example":"top-k 과다/리랭킹 없음 상태로 결과만 보고 운영합니다.","evidence_level":"Research/official pattern"}'::jsonb) on conflict(id) do update set title=excluded.title,symptom=excluded.symptom,root_cause=excluded.root_cause,corrected_example=excluded.corrected_example,prevention=excluded.prevention,test_eval=excluded.test_eval,source_refs=excluded.source_refs,last_verified=excluded.last_verified,metadata=excluded.metadata;
insert into public.failure_patterns(id,title,symptom,root_cause,corrected_example,prevention,test_eval,source_refs,last_verified,metadata) values ('failure-18','Bad chunking','중요 조항/문맥이 조각 경계에서 손실','고정 길이만 사용','문서 구조/overlap/late chunking 실험','문서 구조/overlap/late chunking 실험','실패 재현용 작은 eval case를 만들고 변경 전/후의 실패율을 비교하세요.',array['anthropic-eval']::text[],'2026-09-21'::date,'{"type":"anti_pattern","bad_example":"고정 길이만 사용 상태로 결과만 보고 운영합니다.","evidence_level":"Research/official pattern"}'::jsonb) on conflict(id) do update set title=excluded.title,symptom=excluded.symptom,root_cause=excluded.root_cause,corrected_example=excluded.corrected_example,prevention=excluded.prevention,test_eval=excluded.test_eval,source_refs=excluded.source_refs,last_verified=excluded.last_verified,metadata=excluded.metadata;
insert into public.failure_patterns(id,title,symptom,root_cause,corrected_example,prevention,test_eval,source_refs,last_verified,metadata) values ('failure-19','Embedding mismatch','검색이 사용자 용어를 못 잡음','도메인/언어에 맞지 않는 embedding','hybrid search + eval set','hybrid search + eval set','실패 재현용 작은 eval case를 만들고 변경 전/후의 실패율을 비교하세요.',array['anthropic-eval']::text[],'2026-09-21'::date,'{"type":"anti_pattern","bad_example":"도메인/언어에 맞지 않는 embedding 상태로 결과만 보고 운영합니다.","evidence_level":"Research/official pattern"}'::jsonb) on conflict(id) do update set title=excluded.title,symptom=excluded.symptom,root_cause=excluded.root_cause,corrected_example=excluded.corrected_example,prevention=excluded.prevention,test_eval=excluded.test_eval,source_refs=excluded.source_refs,last_verified=excluded.last_verified,metadata=excluded.metadata;
insert into public.failure_patterns(id,title,symptom,root_cause,corrected_example,prevention,test_eval,source_refs,last_verified,metadata) values ('failure-20','Missing reranker','검색 후보는 많지만 상위 근거 품질이 낮음','retriever 한 단계로 끝냄','reranker/metadata filter 비교','reranker/metadata filter 비교','실패 재현용 작은 eval case를 만들고 변경 전/후의 실패율을 비교하세요.',array['anthropic-eval']::text[],'2026-09-21'::date,'{"type":"anti_pattern","bad_example":"retriever 한 단계로 끝냄 상태로 결과만 보고 운영합니다.","evidence_level":"Research/official pattern"}'::jsonb) on conflict(id) do update set title=excluded.title,symptom=excluded.symptom,root_cause=excluded.root_cause,corrected_example=excluded.corrected_example,prevention=excluded.prevention,test_eval=excluded.test_eval,source_refs=excluded.source_refs,last_verified=excluded.last_verified,metadata=excluded.metadata;
insert into public.failure_patterns(id,title,symptom,root_cause,corrected_example,prevention,test_eval,source_refs,last_verified,metadata) values ('failure-21','Hallucinated citations','존재하지 않거나 틀린 출처를 생성','citation validator 없음','source_id allowlist + URL validation','source_id allowlist + URL validation','실패 재현용 작은 eval case를 만들고 변경 전/후의 실패율을 비교하세요.',array['anthropic-eval']::text[],'2026-09-21'::date,'{"type":"anti_pattern","bad_example":"citation validator 없음 상태로 결과만 보고 운영합니다.","evidence_level":"Research/official pattern"}'::jsonb) on conflict(id) do update set title=excluded.title,symptom=excluded.symptom,root_cause=excluded.root_cause,corrected_example=excluded.corrected_example,prevention=excluded.prevention,test_eval=excluded.test_eval,source_refs=excluded.source_refs,last_verified=excluded.last_verified,metadata=excluded.metadata;
commit;
